### ISSUE TITLE
Ensure finalizers are removed when a node is deleted from the cluster

### ISSUE THREAD

**Issue by palexster** [liqotech/liqo#1009]
#### What happened:

When a node is removed from a cluster during a scale-down, its corresponding finalizer on the tunnel-endpoint is not removed. This behavior makes the unpeering process hang when trying to delete the tunnelEndpoint resource.

#### What you expected to happen:

The unpeer process to complete successfully.

#### How to reproduce it (as minimally and precisely as possible):

1. Create a managed cluster.
2. Peer with another cluster.
2. Scale down.
3. Unpeer.

#### Environment:
- Liqo version: v0.3.2-alpha3
- Kubernetes version (use `kubectl version`): 1.20.11
- Cloud provider or hardware configuration: AKS/GKE/EKS

#### Strategies:

- [ ] Enforce the clean-up when the liqo-route instance is Terminating
- [ ] Check during liqoctl delete cluster if there are pending finalizers and remove them if they are orphaned.

**Comment by giorio94** [comment]
Fixed by #1499
