### ISSUE TITLE
kubectl run -it does not work with offloaded pods

### ISSUE THREAD

**Issue by giorio94** [liqotech/liqo#1023]
#### What happened:

Trying to run a pod in a remote cluster through `kubectl run -it ...` did not result in the shell correctly attached, and instead led to a pod in CrashLoopBackoff status.

#### What you expected to happen:

The shell should be attached correctly to the remote pod.

#### How to reproduce it (as minimally and precisely as possible):

1. liqoctl offload namespace default --pod-offloading-strategy=Remote
2. kubectl run ubuntu --image=ubuntu -n default -it --rm -- /bin/sh
3. Observe that the shell is not attached correctly

#### Anything else we need to know?:

The kubelet emitted the following log line:
```
I1207 18:53:11.207826       1 klogv2.go:71] 404 request not found [uri=/attach/default/ubuntu/ubuntu?input=1&output=1&tty=1 vars=map[]]
```

#### Environment:
- Liqo version: 0.3.2-beta1
- Kubernetes version (use `kubectl version`): 1.21.0
- Cloud provider or hardware configuration: Kubeadm (on premise)
- Network plugin and version: Calico
- Install tools: liqoctl + helm
- Others: None

**Comment by aleoli** [comment]
Closing as fixes
