### ISSUE TITLE
Only 1 node with GPU resource is showed on virtual node, other nodes' GPU are not

### ISSUE THREAD

**Issue by jalola** [liqotech/liqo#1052]
#### What happened:

I have 2 clusters peered by Liqo. On remote cluster, I added 4 nodes, each has 1 GPU, 
All total CPU, RAM, #POD on virtual node of local cluster are summed correctly. However, total GPU is not as the image showed below, total GPU is only 1.

```
export KUBECONFIG=~/.kube/config-liqo-eks-test-2
kubectl get node
NAME                                                STATUS   ROLES    AGE     VERSION
ip-192-168-44-202.ap-southeast-1.compute.internal   Ready    <none>   3m23s   v1.19.15-eks-9c63c4 #1 GPU
ip-192-168-60-162.ap-southeast-1.compute.internal   Ready    <none>   3m23s   v1.19.15-eks-9c63c4 #1 GPU
ip-192-168-70-120.ap-southeast-1.compute.internal   Ready    <none>   14d     v1.19.15-eks-9c63c4
ip-192-168-72-240.ap-southeast-1.compute.internal   Ready    <none>   3m23s   v1.19.15-eks-9c63c4 #1 GPU
ip-192-168-84-190.ap-southeast-1.compute.internal   Ready    <none>   3m23s   v1.19.15-eks-9c63c4 #1 GPU

export KUBECONFIG=~/.kube/config-liqo-eks-test-3
kubectl get node                                
NAME                                                STATUS   ROLES    AGE    VERSION
ip-192-168-79-162.ap-southeast-1.compute.internal   Ready    <none>   6d3h   v1.19.15-eks-9c63c4
liqo-c35ea397-925d-4e96-9b21-4c41f2539042           Ready    agent    3m8s   v1.19.13-eks-8df270

kubectl describe node liqo-c35ea397-925d-4e96-9b21-4c41f2539042
...
Capacity:
  attachable-volumes-aws-ebs:  156
  cpu:                         31330m
  ephemeral-storage:           188933193728
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      252697M
  nvidia.com/gpu:              1
  pods:                        232
Allocatable:
  attachable-volumes-aws-ebs:  156
  cpu:                         31330m
  ephemeral-storage:           188933193728
  hugepages-1Gi:               0
  hugepages-2Mi:               0
  memory:                      252697M
  nvidia.com/gpu:              1
  pods:                        232
...
```

#### What you expected to happen:
Total GPU on virtual node of local cluster must be a sum of all nodes on remote cluster.

#### How to reproduce it (as minimally and precisely as possible):

* Create 2 cluster
* Peer them with Liqo
* Add multiple GPU node to remote cluster

#### Anything else we need to know?:

I tried this on EKS-EKS and EKS-KubeADM (on-prem). Both have same issue

#### Environment:
- Liqo version: v0.3.2-beta.2
- Kubernetes version (use kubectl version): v1.21.0
- Cloud provider or hardware configuration: 2 EKS clusters, 1 EKS - KubeADM (on-prem)
- Network plugin and version:
- Install tools: liqoctl

**Comment by CapacitorSet** [comment]
Could you please edit the deployment for `liqo-controller-manager` to add the flag `--v=4` and post the logs?

**Comment by jalola** [comment]
After I add flag `--v=4`, #GPU on virtual node is updated correctly. But after that, if I update the node (remove or add), virtual doesn't update.

Here is the log
[liqo-controller-manager-log-2.txt](https://github.com/liqotech/liqo/files/7867953/liqo-controller-manager-log-2.txt)
