### ISSUE TITLE
GKE deployment fails when cluster is regional

### ISSUE THREAD

**Issue by aacecandev** [liqotech/liqo#1104]
#### What happened:

When installing in a regional GKE cluster, liqoctl fails to communicate with the googleapi because it is using the `zone` flag, returning the following error.

```
* Initializing installer... 🔌 
* Retrieving cluster configuration from cluster provider... 📜  
Error: googleapi: Error 400: 'zone' field cannot be used to access GKE regional clusters. Use 'name' field instead., badRequest
```

liqoctl doesn't provide an appropriate flag to specify whether the GKE cluster is regional or zonal, only providing a flag to provide the location of a zonal cluster. 

#### What you expected to happen:

liqoctl being able to communicate with a regional (multi-zone) GKE cluster to install liqo

I'm not a Go developer, but I think it could be something related [to this function](https://github.com/liqotech/liqo/blob/c1d9147139fb932365983932a4875b67f94bc1b8/pkg/liqoctl/install/gke/provider.go#L146) that is later [invoked here](https://github.com/liqotech/liqo/blob/c1d9147139fb932365983932a4875b67f94bc1b8/pkg/liqoctl/install/gke/provider.go#L127)

#### How to reproduce it (as minimally and precisely as possible):

* Create a credentials file with the following content and source it to env

```
export GKE_SERVICE_ACCOUNT_ID=<service-account-name
export GKE_PROJECT_ID=<project_name>
export GKE_SERVICE_ACCOUNT_PATH=<path-to-service-account-key-json-file>
export GKE_CLUSTER_ZONE=if tried both <regional-cluster-region> / <regional-cluster-default-node-zones> 
export GKE_CLUSTER_ID=<cluster-name>
```

* Execute installation

```
liqoctl install gke --only-output-values --cluster-id ${GKE_CLUSTER_ID} --credentials-path ${GKE_SERVICE_ACCOUNT_PATH} --project-id {GKE_PROJECT_ID} --zone ${GKE_CLUSTER_ZONE} --cluster-name <arbitraty-name>
```

#### Environment:
- Liqo version: Current Liqoctl client version: v0.3.2
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.12-gke.1500", GitCommit:"d32c0db9a3ccd0ac73b0b3abd0532505217b376e", GitTreeState:"clean", BuildDate:"2021-11-17T09:30:02Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1

- Cloud provider or hardware configuration:

Cloud provider = GCP/GKE

OS = Ubuntu 20.04

Google Cloud SDK 372.0.0
alpha 2022.02.04
app-engine-java 1.9.94
app-engine-python 1.9.99
beta 2022.02.04
bq 2.0.73
core 2022.02.04
gsutil 5.6

- Network plugin and version: 
- Install tools:
- Others:

**Comment by aleoli** [comment]
Hi @aacecandev!

We will add this functionality in `liqoctl`, you can be able to install it with helm using the workaround described in #1105
