### ISSUE TITLE
[Feature] Graceful deletion of Advertisement and virtual-kubelet

### ISSUE THREAD

**Issue by fraborg** [LiqoTech/liqo#113]
**Description**
When we delete an Advertisement, the deployment of the linked virtual-kubelet is deleted as well because of OwnerReferece, and this deletion triggers the deletion of the virtual-node.
Doing so, the resources that have been created on the foreign cluster are not cleaned up: therefore, the behaviour we would like to have is the opposite:
1. delete all resources on foreign cluster
2. delete the virtual-node
3. delete the virtual-kubelet deployment
4. delete the Advertisement

**Proposed solution**
Set a finalizer on the Advertisement, which triggers the virtual-kubelet: it deletes the entry linked to the Advertisement in the NamespaceNattingTable. This triggers the deletion of all resources created on the foreign cluster by the reflector. After that, we can proceed with the deletion of the Advertisement (and its genealogy).

**Comment by aleoli** [comment]
It has been addressed
