### ISSUE TITLE
Uninstalling Liqo

### ISSUE THREAD

**Issue by github6535** [liqotech/liqo#1221]
#### What happened:
When doing 

liqoctl uninstall <cluster-name> -v

the logs from "liqo-pre-delete" are

I0502 09:38:07.411122       1 main.go:58] Loading dynamic client: /.kube/config
I0502 09:38:07.411376       1 main.go:66] Loaded dynamic client: /.kube/config
I0502 09:38:07.427100       1 deletion.go:36] Unjoin 0 ForeignClusters
I0502 09:38:07.427131       1 main.go:80] Foreign Cluster unjoin operation has been correctly performed
I0502 09:38:07.427140       1 wait.go:32] Waiting for Liqo Resources to be correctly deleted
I0502 09:38:12.429603       1 wait.go:106] Waiting for tunnelendpoints.net.liqo.io instances with  labels to be correctly deleted
I0502 09:38:12.432179       1 wait.go:106] Waiting for networkconfigs.net.liqo.io instances with  labels to be correctly deleted
I0502 09:38:12.432867       1 wait.go:117] All incoming or outgoing peering are disabled
I0502 09:38:12.435682       1 wait.go:106] Waiting for nodes instances with liqo.io/type=virtual-node labels to be correctly deleted
I0502 09:38:12.435708       1 wait.go:57] tunnelendpoints.net.liqo.io instances with "" labels correctly deleted
I0502 09:38:12.435715       1 wait.go:57] networkconfigs.net.liqo.io instances with "" labels correctly deleted
I0502 09:38:12.435721       1 wait.go:57] nodes instances with "liqo.io/type=virtual-node" labels correctly deleted
I0502 09:38:12.435727       1 wait.go:64] All peerings have been correctly teared down
I0502 09:38:12.440349       1 wait.go:32] Waiting for Liqo Resources to be correctly deleted
I0502 09:38:17.445333       1 wait.go:106] Waiting for foreignclusters.discovery.liqo.io instances with  labels to be correctly deleted
I0502 09:38:17.446265       1 wait.go:106] Waiting for namespaceoffloadings.offloading.liqo.io instances with  labels to be correctly deleted
I0502 09:38:22.447389       1 wait.go:106] Waiting for namespaceoffloadings.offloading.liqo.io instances with  labels to be correctly deleted
I0502 09:38:27.447466       1 wait.go:106] Waiting for namespaceoffloadings.offloading.liqo.io instances with  labels to be correctly deleted
I0502 09:38:32.447766       1 wait.go:106] Waiting for namespaceoffloadings.offloading.liqo.io instances with  labels to be correctly deleted
I0502 09:38:37.447213       1 wait.go:106] Waiting for namespaceoffloadings.offloading.liqo.io instances with  labels to be correctly deleted
I0502 09:38:42.447811       1 wait.go:106] Waiting for namespaceoffloadings.offloading.liqo.io instances with  labels to be correctly deleted
I0502 09:38:47.446167       1 wait.go:106] Waiting for namespaceoffloadings.offloading.liqo.io instances with  labels to be correctly deleted
I0502 09:38:52.447703       1 wait.go:106] Waiting for namespaceoffloadings.offloading.liqo.io instances with  labels to be correctly deleted
I0502 09:38:57.447738       1 wait.go:106] Waiting for namespaceoffloadings.offloading.liqo.io instances with  labels to be correctly deleted
I0502 09:39:02.447978       1 wait.go:106] Waiting for namespaceoffloadings.offloading.liqo.io instances with  labels to be correctly deleted
I0502 09:39:07.448078       1 wait.go:106] Waiting for namespaceoffloadings.offloading.liqo.io instances with  labels to be correctly deleted
I0502 09:39:12.447546       1 wait.go:106] Waiting for namespaceoffloadings.offloading.liqo.io instances with  labels to be correctly deleted
I0502 09:39:17.448693       1 wait.go:106] Waiting for namespaceoffloadings.offloading.liqo.io instances with  labels to be correctly deleted
I0502 09:39:22.447028       1 wait.go:106] Waiting for namespaceoffloadings.offloading.liqo.io instances with  labels to be correctly deleted
I0502 09:39:27.448470       1 wait.go:106] Waiting for namespaceoffloadings.offloading.liqo.io instances with  labels to be correctly deleted

and because of that Liqo can't be uninstalled.

#### What you expected to happen:
Uninstall Liqo

#### How to reproduce it (as minimally and precisely as possible):
1. Install Liqo
2. Add and remove new Liqo clusters
3. Remove some CRDs, finalizers, etc (it's hard to reproduce, it was many times)
4. Uninstall Liqo

#### Environment:
- Liqo version: fbc678ed8c4e7097883eaae07742b4805de9075e

- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.15-eks-9c63c4", GitCommit:"9c63c4037a56f9cad887ee76d55142abd4155179", GitTreeState:"clean", BuildDate:"2021-10-20T00:21:03Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
EKS

- Network plugin and version:
602401143452.dkr.ecr.eu-west-1.amazonaws.com/amazon-k8s-cni-init:v1.7.5-eksbuild.1

- Install tools:
- Others:

**Comment by giorio94** [comment]
Hi @github6535 

The reason causing the uninstallation process to hang is that some of your namespaces are still selected for offloading.  To make it end successfully, you can proceed removing all `NamespaceOffloading` resources from the offloaded namespaces (if you used `liqoctl offload`) and unlabeling the namespaces (in case you used the `liqo.io/enabled=true` label). Then, you can re-run the uninstallation process.

This is a known limitation of the current version of Liqo/liqoctl, and we are working to improve it.

**Comment by github6535** [comment]
Hi giorio94

One time it worked. Uninstalled Liqo this way. Installed Liqo again. After that the resources are still on the cluster.

kubectl get tunnelendpoints.net.liqo.io -A                                                             
NAMESPACE                                NAME                         PEERING CLUSTER ID                     BACKEND TYPE   CONNECTION STATUS   AGE
liqo-tenant-dev-cluster-tf-6fe012        dev-cluster-tf-6fe012        76443e1b-xxxxxxxx-ae7d-02b2aeee793b   wireguard      connected           40d
liqo-tenant-dev-cluster-tf-91c7a9        dev-cluster-tf-91c7a9        4493b0e7-xxxxxxxx-77382536594a   wireguard      connected           15d
liqo-tenant-eu-dev-eks-unstable-88cc77   eu-dev-eks-unstable-88cc77   6ae052be-xxxxxxxx-b24a-1747c8ff44cf   wireguard      connected           19d

It's not possible to delete them, becasue removing finalizers is now not possible, because of this error message:

kubectl -n liqo-tenant-dev-cluster-tf-6fe012 edit tunnelendpoints.net.liqo.io dev-cluster-tf-6fe012 

error: tunnelendpoints.net.liqo.io "dev-cluster-tf-6fe012" could not be found on the server

**Comment by giorio94** [comment]
Looks definitely strange to me. If the resource is still there you should be able to edit it, otherwise it should have already disappeared. Could you double check for possible typos in the namespace or resource names?

**Comment by github6535** [comment]
Checked triple times. Copy pasted names. Earlier it worked.

We will have no issues with Liqo because we are migrating to new eks.

**Comment by giorio94** [comment]
Closing, as apparently solved. @github6535 feel free to reopen if necessary.

**Comment by ri0day** [comment]
thanks @giorio94  give me information in slack.

for someone end of  uninstall liqo manually ,the follwoing resources need remove:
kubectl get all -n liqo  
kubectl get secret -n liqo  
kubectl get sa -n liqo
kubectl get cm -n liqo 
kubectl get apiservice |grep liqo

kubectl get crds |grep liqo 
if you can not delete crd ,use 
`kubectl patch crd/<crd-name> -p '{"metadata":{"finalizers":[]}}' --type=merge` modify finalizer,delete again

kubectl get clusterrole |grep liqo
kubectl get clusterrolebinding |grep liqo
kubectl get validatingwebhookconfigurations|grep liqo
kubectl get mutatingwebhookconfigurations|grep liqo
