### ISSUE TITLE
EKS and --output-only-values not working

### ISSUE THREAD

**Issue by jschwartzy** [liqotech/liqo#1235]
#### What happened:
In our organization, we don't use AWS IAM Users, we use an external authentication provider and then use IAM Role assumption. To use Liqo, we'd like to go down the Helm chart install route.

However, this command:

`liqoctl install eks --eks-cluster-name my-cluster  --region us-west-2  --output-only-values --dump-values-path ./liqo/values.yaml`

Does nothing.  The app just returns to the command prompt and no `values.yaml` file is created.

#### What you expected to happen:

`values.yaml` file created in the location specified.

#### How to reproduce it (as minimally and precisely as possible):
1. Setup an EKS cluster
2. Export the appropriate AWS/AWS_PROFILE credentials
3. Run the command listed above.

#### Environment:
- Liqo version: `Current Liqoctl client version: v0.4.0`
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.11", GitCommit:"38d3c1f3d5306401bcf39a71bad3b5a5106033d7", GitTreeState:"clean", BuildDate:"2022-03-16T14:08:11Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.15-eks-0d102a7", GitCommit:"a8ff0230f2c155701a76c41fdcbddff180dc1833", GitTreeState:"clean", BuildDate:"2022-02-17T16:47:50Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: AWS 
- Network plugin and version: AWS CNI v1.8.0

**Comment by jschwartzy** [comment]
Typo in the command the correct switch is `--only-output-values`.
Any switch `liqoctl` doesn't recognize just quits the app.

**Comment by giorio94** [comment]
Hi @jschwartzy,

Thanks for the feedback, this is a known limitation in liqoctl. We are currently working on a completely refactored version of it (#1230), which also includes better error feedback. It is expected to be released in the next few weeks.
