### ISSUE TITLE
GKE Cluster peering fails in auth phase

### ISSUE THREAD

**Issue by paragw-ck** [liqotech/liqo#1330]
#### What happened:
Created 2 VPCs in a single GCP project in us-central-1 region. Internal IPV4 ranges are purposely the same for both (10.220.0.0/16)
Created 2 Zonal GKE clusters each tied to one of the above VPCs - one has control plan in us-central-1a and other 1f.
Installed liqo on both clusters - everything came up fine. The endpoints (auth/gateway etc.) are accessible over Internet using the External Load Balancer
Tried to establish both in-band and out-of-band peering but both failed authentication - 
` ERRO  Authentication to the remote cluster "peer-cluster-1" failed: timed out waiting for the condition`

#### What you expected to happen:
Peering was successful.

#### How to reproduce it (as minimally and precisely as possible):
As per above it should be easy to reproduce.

#### Anything else we need to know?:
This might not necessarily a bug - this is mostly me trying to understand the workings of liqo. One curiosity I had was what happens when IP ranges overlap between 2 clusters in different VPCs in the same project. I am trying to find out why this doesn't work for the out of band case - my expectation was that since everything goes out of band the auth should have worked. However I see below errors in the logs that suggest things are happening over local IPs -

`controller-manager E0711 21:49:19.769599       1 foreign-cluster-controller.go:219] Post "https://10.221.0.2:443/identity/certificate": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

`auth 2022/07/12 11:19:11 http: TLS handshake error from 10.220.0.8:47754: read tcp 10.122.0.2:8443->10.220.0.8:47754: read: connection reset by peer`

#### Environment:
- Liqo version: 0.5.2
- Kubernetes version (use `kubectl version`): v1.22.8-gke.202
- Cloud provider or hardware configuration: GCP/GKE
- Network plugin and version:
- Install tools: liqoctl 0.5.2
- Others:

**Note** I am mostly trying to understand a) why this does not work from a networking standpoint for the out of band case and b) what debugging process can be used to diagnose something like this. (I also did not see any specific requirements for GKE clusters that suggest this is not a workable use case - so it would be good to update the docs if that's the case.)

**Comment by aleoli** [comment]
Hi @paragw-ck! In the out-of-band peering, it should contact the auth-service LoadBalancer IP. Your issue can be a dirty state after a failed in-band peering.

Make sure that no `networkconfig` and/or `tunnelendpoint` resources are present in your `liqo-tenant-*` namespace and then you can edit your `foreigncluster` resources (on both clusters, if any) making sure that:
* the `spec.networkingEnabled ` flag is set to "Yes"
* the `spec. foreignAuthUrl ` is set to your LoadBalancer IP (of the other cluster)
* the `spec. foreignProxyUrl ` is not set

Then, we must understand why the authentication didn't work in the in-band scenario.

I guess the log `ERRO Authentication to the remote cluster "peer-cluster-1" failed: timed out waiting for the condition` is a failed in-band peering. This can be due to a networking issue between the two clusters. The requirements are 1) reachable services, 2) allowed UDP traffic, and 3) MTU accordingly set.

To answer your curiosity: when two clusters have the same pod CIDR, liqo transparently remaps it using a double NAT and a remapped pod CIDR. For example, if you have a pod with IP 10.10.0.3 in a cluster with pod CIDR 10.10.0.0/16, it can be remapped by another cluster as 10.11.0.0/16, and you will reach that pod with the IP 10.11.0.3

**Comment by paragw-ck** [comment]
Hi @aleoli - thanks for getting back to me. I got past the Auth issue - I am now able to authenticate to the peer cluster. Thank you for pointing me towards the right direction. (I had to disable control plane authorized networks btw to get past.)

```
INFO  Peering enabled
 INFO  Authenticated to cluster "peer-cluster-1"
 ERRO  Failed establishing networking to the remote cluster "peer-cluster-1": timed out waiting for the condition
```

However it now fails on establishing networking. The foreign cluster stays like this - 

NAME             OUTGOING PEERING   INCOMING PEERING   NETWORKING   AUTHENTICATION   AGE
peer-cluster-1   Established        None               Pending      Established      22m

I ran some Network Connectivity Tests in GKE and the required network paths are working.

However I ended up blowing up the old clusters and recreating them without GKE DataPlane V2 - as many of the Dataplane V2 specific network functionality related pods were failing to come up. I am now running into installation issue -

```
liqoctl install gke --project-id ${GKE_PROJECT_ID} --context ${GKE_CLUSTER_CONTEXT} \
    --cluster-id ${GKE_CLUSTER_ID} \
    --zone ${GKE_CLUSTER_ZONE} \
    --credentials-path ${GKE_SERVICE_ACCOUNT_PATH}
 INFO  Installer initialized
 ERRO  Error retrieving configuration: failed validating Pod CIDR "10.122.0.0/16": pod "calico-node-vertical-autoscaler-78786cd6df-4mj49" does not match the provided Pod CIDR (IP: 10.192.1.2)
```

So it looks like later Calico versions changed and they use their own IPAM thing to allocate different Pod IPs for calico pods than the PodCIDR ones. Is this something that's going to be supported? Same question on GKE Dataplane V2 which I think uses cilium.

I can create another issue for the Calico problem if needed - just wanted to clear this one out first.

**Comment by aleoli** [comment]
Hi @paragw-ck! It seems that the PodCIDR retrieved from the google APIs is different from the one calico uses. We should add a flag to override this value.

At the moment, you can workaround od this in two ways:
1. add the `--only-output-values` flag to your command to get the values.yaml file, manually modify the podCIDR and serviceCIDR values, and then install it with helm
2. use the liqoctl generic provider with `liqoctl install --api-server-url=<API-SERVER-URL> --pod-cidr=<POD-CIDR> --service-cidr=<SERVICE-CIDR>`

**Comment by tsusadivyago** [comment]
Hi,

I am also facing the same issue _unable to peer 2 GKE clusters in Out-band mode_. 
The two Gke clusters api server is public and there are no firewall restrictions.

Are there any settings to be checked, Are there any logs that I should check to debug further?

_Logs:_
INFO  Peering enabled                                                               
 INFO  Authenticated to cluster "peere-gke-dev"                                      
 ERRO  Failed establishing networking to the remote cluster "peere-gke-dev": timed out waiting for the condition

_foreignclusters:_
peere-gke-dev   Established        Established        Pending      Established      17h

_tunnelendpoints:_
Status:           Connecting
Status Message:   Waiting VPN connection to be established

**Comment by paragw-ck** [comment]
> 2\. liqoctl install --api-server-url=<API-SERVER-URL> --pod-cidr=<POD-CIDR> --service-cidr=<SERVICE-CIDR>

This fails with the same error btw. 
```ERRO  Error retrieving configuration: failed validating Pod CIDR```

So I assume helm install will fail similarly as well. I guess we really need an override flag or even just accept is as normal use case given GKE uses Calico and so do many other installations.

**Comment by paragw-ck** [comment]
Ok, so I got further along after commenting out the pkg/liqoctl/install/validation.go:validatePodCIDR function. 

Now in trying to offload a namespace I am facing below issue - looks like it is not able to reach the controller manager. (However exec'ing into the liqo-auth pod for e.g. I can connect to the controller-manger:9443 endpoint. So I am not sure from where the connectivity is failing to the cm svc.

```
ERRO  Failed enabling namespace offloading: Error from server (InternalError): Internal error occurred: failed calling webhook "nsoff.validate.liqo.io": failed to call webhook: Post "https://liqo-controller-manager.liqo.svc:9443/validate/namespace-offloading?timeout=10s": context deadline exceeded
```

**Comment by paragw-ck** [comment]
https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters#view_firewall_rules - after adding the firewall rule for private cluster control plan to reach into 9443 service IP webhook succeeded and namespace was offloaded. 

Closing this issue. Please create a new one if you still have peering problems.
