### ISSUE TITLE
kubectl run/exec fails with x509 error due to invalid hostname

### ISSUE THREAD

**Issue by paragw-ck** [liqotech/liqo#1334]
#### What happened:

- Setup a provider and a consumer cluster in GKE, had to disable the PodCIDR validation check as it is quite normal in GKE for PodIPs to be different from the Cluster PodCIDRs. 
- Created and offloaded a namespace in the one cluster and offloaded it to the other cluster successfully.
- Ran a pod like below 
``` kubectl --context=cluster-1 -n offtest run nginx2 -it --image=docker.io/clearlinux/nginx:latest -- /bin/bash 
``` 
This failed with below error -
```
If you don't see a command prompt, try pressing enter.
Error attaching, falling back to logs: error dialing backend: x509: certificate is valid for 10.192.0.2, not 10.192.1.2
Error from server: Get "https://10.192.1.2:10250/containerLogs/offtest/nginx2/nginx2": x509: certificate is valid for 10.192.0.2, not 10.192.1.2
```
Where the 10.192.1.2 IP belongs to liqo-cluster-1 virtual node and none of the node IPs have the 10.192.0.2 IP for which the cert is provisioned. 

#### What you expected to happen:
Pod was created and attached to and I see a bash prompt.

#### How to reproduce it (as minimally and precisely as possible):
- Create two GKE clusters in a single GCP project with 2 separate VPCs containing overlapping IPV4 ranges.
- Setup Liqo, offload a namespace and try to run a pod in the offloaded namespace using kubectl exec
#### Anything else we need to know?:
When adding a Node Pool the Node Pool Pod Address Range might need to be overridden to be different from the Cluster's.

#### Environment:
- Liqo version: 0.5.2
- Kubernetes version (use `kubectl version`): v1.22.8-gke.202
- Cloud provider or hardware configuration: Google Cloud / GKE
- Network plugin and version: 
- Install tools: Custom compiled liqoctl to disable PodCIDR validation.
- Others:

**Comment by paragw-ck** [comment]
Would [this](https://10.192.1.2:10250/) be the code of interest? I am trying to understand how we land here. 

I tried forcing change of the virtual node and now I get the same error - except the API Server (presumably) is calling 10250 on the virtual node's new IP but it still gets back the same cert with the wrong IP 10.192.0.2.

**Comment by giorio94** [comment]
Hi @paragw-ck,

It seems you hit a bug in the certification generation process for the liqo virtual kubelet, which causes the certificate not to be recreated when the virtual kubelet pod is restarted (and thus changes IP). 

As a short term fix, I would suggest to remove the secret located in the liqo-tenant-*** namespace and named after the virtual node name, and then restart the virtual kubelet pod. That way, a new certificate is recreated with the correct values, and logs/exec should work. In the meanwhile, we work towards a complete fix.

**Comment by giorio94** [comment]
Yes, that is a known problem, and it is tracked by #1023.
