### ISSUE TITLE
Unable to download older version of liqo

### ISSUE THREAD

**Issue by sandyvanam** [liqotech/liqo#1343]
curl --fail -LS "[https://github.com/liqotech/liqo/releases/download/v0.4.0/liqoctl-linux-amd64.tar.gz"](https://github.com/liqotech/liqo/releases/download/v0.4.0/liqoctl-linux-amd64.tar.gz%22) | tar -xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404

**Comment by sonarypt** [comment]
It's not a bug. You should use this link [https://github.com/liqotech/liqo/releases/download/v0.4.0/liqoctl-linux-amd64](https://github.com/liqotech/liqo/releases/download/v0.4.0/liqoctl-linux-amd64) (without `.tar.gz`, and then `tar -xz`). Everything should be fine.

**Comment by giorio94** [comment]
Hi @sandyvanam, we modified the v0.4.0 release to include also the `.tar.gz` artifacts for the sake of compatibility with the installation command presented in the documentation.

Still, it is worth mentioning that liqoctl has undergone significant changes between v0.4.0 and v0.5.0, and most of the commands presented in the documentation will not work as is with v0.4.0. For this reason, we suggest upgrading to the latest version of Liqo.
