### ISSUE TITLE
Pod Scheduling issue

### ISSUE THREAD

**Issue by jhuynh08** [liqotech/liqo#1353]
#### What happened:
I noticed that when I deploy the gke microservice demo that all the pods were deployed to the remote cluster only. The namespace was offloaded using default settings (LocalAndRemote). 
#### What you expected to happen:
For some pods to be evenly distributed between local and remote nodes.
#### How to reproduce it (as minimally and precisely as possible):
1. Peered the local and remote nodes
2. Offload the namespace on local and deployed the microservices application from it.
3. Was able to confirm that the pods deployed on remote nodes **only**.
#### Anything else we need to know?:
I can get the pods to schedule if I change the pod scheduling strategy from LocalAndRemote to just Local but that's not I want since I want to schedule the pods to local and remote.
#### Environment:
- Liqo version: v0.5.2
- Kubernetes version (use `kubectl version`): v1.21
- Cloud provider or hardware configuration: AWS
- Network plugin and version:
- Install tools:
- Others:

**Comment by alacuku** [comment]
Hi @jhuynh08, setting the pod scheduling strategy to `LocalAndRemote` will enable pods to be scheduled to local and remote nodes. Liqo does not affect the k8s scheduler which is in charge to decide where the pods will be scheduled. If you are seeing that pods are being schedule all to the remote nodes could be because the `liqo virtual node` advertises much more resources than the local ones. In this scenario the k8s scheduler will prefer the `liqo virtual node` causing the pods to be physically run in the remote nodes.

**Comment by jhuynh08** [comment]
Hi @alacuku, thanks for the quick response. That makes sense. Would there be any way to bypass using the resource as the preferred method and have liqo deploy the pods to local and remote in a round-robin type of fashion?

**Comment by alacuku** [comment]
Well, you can not do that through liqo. But remember that methods such as `nodesSelectors`, `affinity and anti-affinity`, `nodeName` and `pod topology spread constraints` that works with normal nodes are applicable to the `liqo virtual node`. So if you need some pods to be run locally than this is the way to go. 

By using the methods described above you can only target the nodes on the local cluster where you are applying them. Lets say that we have two clusters A and B, and cluster A has a virtual node that maps to cluster B. You can only use the name of `liqo virtual node` in affinities or nodeSelectors and not directly the nodes of cluster B. When a pod arrives to the scheduler to the cluster A it will just consider the local nodes, including the `liqo virtual node`. The scheduler in cluster A does not know about the existence of nodes in cluster B that are accessible through the `liqo virtual node` in cluster A. 

Hopefully this explanation will make sense to you!

**Comment by jhuynh08** [comment]
Ah understood, thank you!
