### ISSUE TITLE
Liqo Peering between aks aks cluster

### ISSUE THREAD

**Issue by AccHimanshu** [liqotech/liqo#1367]
#### What happened:
Liqo installation is working fine. But unable to peer two aks cluster. Authentication error is arising. Can you let us know - with which version of liqo, you have able to successfully peer two aks public clusters.

#### Environment:
- Liqo version: v0.4.0 and v0.5.3
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Network plugin and version:
- Install tools:
- Others:

**Comment by giorio94** [comment]
Closing, since after offline investigation the problem appeared to be due to a connectivity issue between the two clusters, unrelated from liqo.
