### ISSUE TITLE
Issue while offloading an application using pod-offloading-strategy

### ISSUE THREAD

**Issue by Priyaboliset** [liqotech/liqo#1379]
.#### What happened: 
We tried to offload an application on peered clusters using pod-offloading-strategy on Remote, as per strategy it needs to run on only remote but pods are running on local cluster

![liqo-eks](https://user-images.githubusercontent.com/108928747/183571282-4c017a41-3861-41c5-a22b-1352eadaa8e4.PNG)
![liqo-pod-running-gke](https://user-images.githubusercontent.com/108928747/183571285-e1be1e3a-422f-4cb4-88b5-fd95baa4a6d0.PNG)
![liqo-deploy-manifest](https://user-images.githubusercontent.com/108928747/183571288-5724a114-85f7-40b3-8ad9-74127609baa8.PNG)
![liqo-pod-offloading-strategy](https://user-images.githubusercontent.com/108928747/183571289-83fa3ec4-cfdd-4f71-a351-03ea838f0019.PNG)
![liqo-peering](https://user-images.githubusercontent.com/108928747/183571294-3170b732-c56c-484f-bc97-76a07a647ecb.PNG)

#### What you expected to happen:
 Pods should run on remote cluster as per the pod-offloading-strategy

#### Anything else we need to know?:
The steps we performed are below
Step1: Peering is established between AWS and GCP Clusters. (Refer image : liqo-peering.png )
Step2: Created namespace and enabled pod-offloading-strategy on remote. (Refer Image: liqo-pod-offloading-strategy.png)
Step3: Deployed manifest files in GCP cluster (Refer Image: liqo-deploy-manifest.png)
Step4: When I check the pods, All the pods are running in gke cluster only. But ideally it has to run in aws cluster right? (Refer Image: liqo-pod-running-gke.png)
Step5: No pods are listing in eks cluster.(Refer image : liqo-eks.png)
using liqoctl version: v0.4..  Kindly help to resolve the issue asap
Attached all the images for reference above
#### Environment:
- Liqo version: liqoctl version: v0.4
- Kubernetes version (use `kubectl version`):v1.21.14

**Comment by giorio94** [comment]
Hi @Priyaboliset,

Could you please post the yaml of one of the pods that is not scheduled correctly? And the logs of the liqo-webhook?

By the way, I would suggest you to upgrade liqo to the latest version, as we fixed different bugs, and many commands present in the current documentation are incompatible with v0.4.0.
