### ISSUE TITLE
Error installing liqo over kind cluster 

### ISSUE THREAD

**Issue by AccHimanshu** [liqotech/liqo#1393]
Receiving errors as following - 
1) 
~$ liqoctl install kind --cluster-name "kind"
 [SUCCESS]  Configuration loaded                                                                           
 [SUCCESS]  Installer initialized                                                                          
 [SUCCESS]  Chart parameters extracted                                                                     
 [ERROR]  Error installing or upgrading Liqo: "liqo" has no deployed releases 

2) 
$ liqoctl install kind --cluster-name "demo"
 [SUCCESS]  Configuration loaded                                                                           
 [SUCCESS]  Installer initialized                                                                          
 [SUCCESS]  Chart parameters extracted                                                                     
 [ERROR]  Error installing or upgrading Liqo: another operation (install/upgrade/rollback) is in progress

#### Anything else we need to know?:
Please let us know the process to install liqo over kind cluster
#### Environment:
- Liqo version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Network plugin and version:
- Install tools:
- Others:

**Comment by giorio94** [comment]
HI @AccHimanshu,

Could you please provide more details about the issue? I just tried with a new kind cluster (using liqoctl v0.4.0, which is the version I suppose you are using), and everything worked as expected, with no errors.

By the way, it is suggested to use a version of liqoctl that matches the one of liqo you are installing (v0.5.4 in this case).

**Comment by AccHimanshu** [comment]
INFO  Deployment is not ready: liqo/liqo-gateway. 0 out of 1 expected pods are ready      

liqo-gateway-d9f56bf4d-dvncj - this is one pod. Which is not coming up. I think because of which deployment is not ready

**Comment by AccHimanshu** [comment]
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  75s (x2 over 6m19s)  default-scheduler  0/1 nodes are available: 1 Insufficient cpu. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod.

**Comment by giorio94** [comment]
The problem is that there are not enough resources (i.e., CPU) on your machine to start all liqo pods, considering the request values set by liqo. As a workaround, if you cannot use a more powerful machine, you might delete the resource request from all liqo pods once it has been deployed. For the future, that parameter shall be made configurable in the helm chart.

**Comment by AccHimanshu** [comment]
After increasing the CPU size of the machine. Liqoctl was deployed over Kind.
