### ISSUE TITLE
[Feature] Selective resource reflection

### ISSUE THREAD

**Issue by Jibux** [liqotech/liqo#1459]
**Is your feature request related to a problem? Please describe.**
* Ingresses are replicated with their `cert-manager.io/cluster-issuer` annotation. That makes the remote cluster creating certificate requests with letsencrypt HTTP01 challenges that cannot be fulfilled (ingresses hosts fqdn are not pointing to both clusters but only one for each name).
* Secrets and configmaps are replicated too: it can cause security issues.

**Describe the solution you'd like**
Ability to select the resources to offload.

**Describe alternatives you've considered**
Or (for ingresses) do not replicate specific annotations.

**Additional context**
In our case we are only interested in replicating services so we are using pod-offloading-strategy Local for all offloaded namespaces.

**Comment by giorio94** [comment]
Hi @Jibux,

We recently introduced the possibility of skipping the reflection of certain objects through the addition of a dedicated annotation (#1362), and this feature will be part of the next release. Additionally, you can also completely disable the reflection of a certain type of resource (e.g., secrets) at the virtual kubelet level, setting the flag tuning the corresponding number of workers to 0 (e.g., `--secret-reflection-workers=0`)

**Comment by Jibux** [comment]
Thanks @giorio94.
Anyway I was looking through documentation and I did not came across this information. Is it specified somewhere?

**Comment by giorio94** [comment]
That about the annotation is present, although in the latest version given it has not yet been released: https://docs.liqo.io/en/latest/usage/reflection.html

The feature of completely disabling the reflection is not documented AFAIR, but I agree it should be present there.

**Comment by giorio94** [comment]
We extended the documentation with the information about how to completely disable the reflection of a given type of resource type. I'm closing this issue for now, feel free to reopen it if you feel something is still missing.
