### ISSUE TITLE
Get ip in kind

### ISSUE THREAD

**Issue by aleoli** [LiqoTech/liqo#146]
**Describe the bug**
Sometimes, running liqo in kind, discovery component advertises on LAN wrong ip. For example if the correct IP is 172.18.0.x it advertises 192.168.200.x

**To Reproduce**
Run liqo installer in kind cluster

**Comment by palexster** [comment]
hi @aleoli, does #190 affect also this?

**Comment by aleoli** [comment]
Yes, as @alacuku told me, it is working fine on kind now. But I would keep this issue to remember me to do deeper tests on it
