### ISSUE TITLE
Remote Pod offloading strategies are not working for some applications where pvc's are required

### ISSUE THREAD

**Issue by Priyaboliset** [liqotech/liqo#1609]
#### What happened:
We have different clouds in our environment like AWS,AZURE,GCP and we have some terraform modules in our environment. Using local offloading all the modules are working but for remote offloading the modules that has dependencies in creating pvc's are not working for remote offloading.

#### What you expected to happen:
As like local the module should get provisioned for remote offloading strategies for same cloud combinations like AKS-AKS,EKS-EKS and also with cross cloud combinations like AKS-EKS, EKS-AKS

#### Environment:
- Liqo version:
- Client version: v0.6.0
Server version: v0.6.0
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.12", GitCommit:"f941a31f4515c5ac03f5fc7ccf9a330e3510b80d", GitTreeState:"clean", BuildDate:"2022-11-09T17:12:33Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
PVC's are not getting created for remote offload strategies for same and cross cloud combinations

- Others:
Command used for remote pod offloading

#liqoctl offload namespace ***** --namespace-mapping-strategy EnforceSameName --pod-offloading-strategy Remote --selector liqo.io/provider=eks

**Comment by giorio94** [comment]
Hi @Priyaboliset,

Are you using the `liqo` StorageClass for the PVCs?

**Comment by Priyaboliset** [comment]
Hi @giorio94 We are not using any liqo StorageClass for PVC

**Comment by giorio94** [comment]
Sorry for the delay @Priyaboliset. This is the reason why offloaded pods do not start on remote clusters. The liqo storage class is a virtual storage class which abstracts the real ones present in each physical cluster, managing the creation and the binding of the PVCs in the correct location based on where the binding pod is scheduled. You can find more details in the official documentation: https://docs.liqo.io/en/v0.6.1/usage/stateful-applications.html

**Comment by Priyaboliset** [comment]
@giorio94 Thanks for the reply. We can see that pvc's are in pending state with this error added below in the case of EKS clusters
<img width="842" alt="image" src="https://user-images.githubusercontent.com/108928747/209555550-45ea2d40-ec50-415e-afec-9b8373ad78a9.png">
Can you let us know how to enable reflection for the specified cluster on the required namespace


In the case of AKS clusters also we are seeing that pvc's are in pending  state with below error
 Normal   Provisioning          2s (x8 over 96s)   disk.csi.azure.com_csi-azuredisk-controller-7b58b64fdd-gxn5j_dfa0cfe0-2cce-4850-9350-27028f5dfb6f  External provisioner is provisioning volume for claim "priya/test1-jenkins-dev"
  Warning  ProvisioningFailed    2s (x8 over 96s)   disk.csi.azure.com_csi-azuredisk-controller-7b58b64fdd-gxn5j_dfa0cfe0-2cce-4850-9350-27028f5dfb6f  failed to provision volume with StorageClass "default": error generating accessibility requirements: error getting CSINode for selected node "liqo-akspr1-aks-dev": csinode.storage.k8s.io "liqo-akspr1-aks-dev" not found

**Comment by giorio94** [comment]
> Can you let us know how to enable reflection for the specified cluster on the required namespace

Offloading can be enabled using the `liqoctl offload ns` command: https://docs.liqo.io/en/v0.6.1/usage/namespace-offloading.html. Beware that offloading the kube-system namespace is discouraged and typically leads to unintended effects, given that it hosts system-related pods.

> In the case of AKS clusters also we are seeing that pvc's are in pending state with below error
Normal Provisioning 2s (x8 over 96s) disk.csi.azure.com_csi-azuredisk-controller-7b58b64fdd-gxn5j_dfa0cfe0-2cce-4850-9350-27028f5dfb6f External provisioner is provisioning volume for claim "priya/test1-jenkins-dev"
Warning ProvisioningFailed 2s (x8 over 96s) disk.csi.azure.com_csi-azuredisk-controller-7b58b64fdd-gxn5j_dfa0cfe0-2cce-4850-9350-27028f5dfb6f failed to provision volume with StorageClass "default": error generating accessibility requirements: error getting CSINode for selected node "liqo-akspr1-aks-dev": csinode.storage.k8s.io "liqo-akspr1-aks-dev" not found

Are you experiencing this error using the `liqo` storage class?

**Comment by Priyaboliset** [comment]
With storage class it is working, but what need to be done for default storage classes ie., for csi provisioners

**Comment by giorio94** [comment]
Storage classes beside the liqo one are not supported (and likely won't work) for offloaded workloads. This is because they would not know how to create PVs in a different cluster.

**Comment by Priyaboliset** [comment]
With previous liqo version v0.4.0 it is working.. Is this functionality doesn't work in v0.0.6 only?

**Comment by giorio94** [comment]
That looks strange to me (there should have been no changes affecting that AFAIR), but regressions can always happen. Could you please provide the exact steps required to replicate your setup and perform a few tests?
