### ISSUE TITLE
Is it possible to start only the workload offloading function without peering?

### ISSUE THREAD

**Issue by lxm** [liqotech/liqo#1612]
Is it possible to start only the workload offloading function without peering?

**Comment by giorio94** [comment]
No, since the peering phase is responsible for the setup of (a) the appropriate authorizations, (b) the network fabric and (c) the virtual node, all necessary for workload offloading.

**Comment by lxm** [comment]
> No, since the peering phase is responsible for the setup of (a) the appropriate authorizations, (b) the network fabric and (c) the virtual node, all necessary for workload offloading.

the network fabic is complex for quick start or product env.
I want to use (a) and (c) without (b), is that possible?

**Comment by giorio94** [comment]
> I want to use (a) and (c) without (b), is that possible?

Currently not, although we are considering whether that support might be introduced in future releases.

**Comment by lxm** [comment]
> > I want to use (a) and (c) without (b), is that possible?
> 
> Currently not, although we are considering whether that support might be introduced in future releases.

Looking forward to this feature.

If the feature is implemented, users can more freely combine the capabilities provided by liqo.

**Comment by aleoli** [comment]
This is now possible in Liqo; we support selective module activation. [See here docs](https://docs.liqo.io/en/v1.0.0-rc.3/advanced/use-only-offloading.html)
