### ISSUE TITLE
Peering with Private Cluster for AWS to AWS not working

### ISSUE THREAD

**Issue by gauravitdevops** [liqotech/liqo#1620]
What happened:
While setting up private cluster for AWS Cloud and trying to peer it with another AWS Private Cluster facing issue as shown in screenshot.

What you expected to happen:
As per documentation the peering should be established and also as per documentation the communication between two cluster should be the liqo gateway but we found out that the IP it is trying to hit is of API Server/API Control Plane which should be of Liqo Gateway instead. (Screenshot for the same attached)

Anything else we need to know?:
Environment:
Liqo version:

Client version: v0.6.0
Server version: v0.6.0

Cloud: AWS
![image](https://user-images.githubusercontent.com/93724432/211242805-0c7613f1-b764-4e8d-bcd7-35899046977f.png)
![Issue](https://user-images.githubusercontent.com/93724432/211242810-11b163e6-fa26-47f0-93fd-6c837023d7fc.png)

**Comment by giorio94** [comment]
Hi @gauravitdevops,

The error seems to concern the access of the *remote* cluster from your workstation. Can you confirm that you can access it using kubectl from that machine? As stated in the [dedicated documentation page](https://docs.liqo.io/en/v0.6.1/usage/peer.html#in-band-control-plane), the host used to issue the `liqoctl peer in-band` command needs to have access to both clusters at the same time.

I also confirm that, with the in-band peering approach, the cross-cluster communication goes through the liqo gateway. Here, you are observing the peering establishment phase, which requires some initial configurations performed by liqoctl in both clusters to setup the network connectivity, and let the remainder of the process to flow through the VPN tunnel just established.

**Comment by gauravitdevops** [comment]
So in that case private cluster cannot be accommodated into this scenario as they wont have any endpoint which would be open and hence liqoctl peer command will not have access to the cluster hence the peering will not work.
Closing it as what I understand is that we can peer only public clusters only using liqo.
