### ISSUE TITLE
Is it possible to declaratively provision cluster peerings?

### ISSUE THREAD

**Issue by bcarlock-emerge** [liqotech/liqo#1626]
Is there any way to declaratively provision a peering? We're deploying clusters with Terraform and I've been experimenting with writing the secrets and the ForeignCluster. When deployed directly with terraform the ForeignCluster will not connect. However, if I manually peer the clusters with liqoctl, then remove the peering I can recreate the same ForeignCluster object with terraform and the peering will automatically negotiate. Am I missing an object or is there some internal functionality I'm not able to trigger?

**Describe the solution you'd like**
I'd like to see a clear and documented way to peer clusters declaratively.

**Describe alternatives you've considered**
Karmada, Admiralty, Istio, Cillium, + others

**Additional context**

**Comment by aleoli** [comment]
Hi @bcarlock-emerge!

You need to set the outgoingPeeringEnabled flag in the ForeingCluster spec to "Yes" (note that this is a string and not a boolean) in order to enable the peering to the remote cluster, setting this flag you should be able to handle the peering declaratively

Additionally, we are working on a Liqo Terraform provider that will handle both peerings and offloading in a declarative way. We will release it soon

**Comment by bcarlock-emerge** [comment]
Excellent, I look forward to experimenting with the Terraform provider.
I have both outgoing and incoming set to "yes" on both sides, but there is a status message about the tunnel endpoint not existing in the generated namespace, and another that is an auth error. Do I have to manually create the virtual kubelet replica set and service account?

**Comment by aleoli** [comment]
Your configuration seems fine, but you are missing one label in your secrets:

```yaml
labels:
  discovery.liqo.io/auth-token: ""
  discovery.liqo.io/cluster-id: {UUID for memberX}
```

**Comment by bcarlock-emerge** [comment]
Interesting. I added the label and the clusters connected.

What's the function of that label, and why is it blank?

**Comment by aleoli** [comment]
> Edit- Everything is working as intended with a full bootstrap.

Beautiful! 🎉

> What's the function of that label, and why is it blank?

The liqo control plane looks for secrets with that label to select the ones containing authentication tokens. It does not retrieve it by name (here, the only requirement is to be unique, of course) but by label

**Comment by cheina97** [comment]
We added a [Liqo terraform provider](https://registry.terraform.io/providers/liqotech/liqo/latest). An example can be found [here](https://docs.liqo.io/en/v0.7.0/examples/provision-with-terraform.html)
