### ISSUE TITLE
Reflected SA token couldn't access API server on AKS, works on kind.

### ISSUE THREAD

**Issue by lgarcia11** [liqotech/liqo#1646]
#### What happened:

`{"level":"error","ts":1674722989.221408,"msg":"error while waiting for the API server to be reachable","logging_pod":"postgresql-1","error":"Get \"https://kubernetes.default:443/apis/postgresql.cnpg.io/v1/namespaces/liqo-demo/clusters/postgresql\": net/http: TLS handshake timeout","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:127\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management.WaitKubernetesAPIServer\n\tpkg/management/client.go:147\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/initdb.NewCmd.func1\n\tinternal/cmd/manager/instance/initdb/cmd.go:53\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.6.1/command.go:901\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968\nmain.main\n\tcmd/manager/main.go:64\nruntime.main\n\t/opt/hostedtoolcache/go/1.19.4/x64/src/runtime/proc.go:250"}
Error: error while waiting for the API server to be reachable: Get "https://kubernetes.default:443/apis/postgresql.cnpg.io/v1/namespaces/liqo-demo/clusters/postgresql": net/http: TLS handshake timeout`

#### How to reproduce it (as minimally and precisely as possible):
Use AKS as consumer. Deploy an cloudnative-pg cluster.

#### Anything else we need to know?:
Tested on kind and works as expected.

#### Environment:
- Liqo version: 5ee601a53bcc5f69d2ad1e7d177db37da3fe9acd
- Kubernetes version (use `kubectl version`): 1.25.4
- Cloud provider or hardware configuration: AKS 
- Network plugin and version: kubenet

**Comment by aleoli** [comment]
Hi @lgarcia11!

I think your issue is related to https://github.com/liqotech/liqo/issues/1571

**Comment by lgarcia11** [comment]
> Hi @lgarcia11!
> 
> I think your issue is related to #1571

thanks, it's related. Closing in favor of #1571
