### ISSUE TITLE
[Feature] Support of the Istio mesh 

### ISSUE THREAD

**Issue by Dima-Diachenko-work** [liqotech/liqo#1651]
Hello guys, 

My team and I are building "Production ready" multiregion cluster in the Azure using AKS.
We created a test example with Liqo aboard. Awesome solution, many thanks! 

We use [cluster peering and namespace offloading](https://docs.liqo.io/en/stable/examples/offloading-with-policies.html) for Deployments.
And we have issue with network routing using Istio Ingress and Virtual Services.

Access to the applications inside the cluster took 10, 20 and sometimes 30 seconds when we enable `Remote` or `LocalAndRemote` Namespace offloading strategy.

As a result of our troubleshooting, we can definitely say that this is a network issue based on discovery in the cluster federation. 

I could describe in details the issue that we faced, but for now I have a preliminary question below.
Maybe we're doing something wrong with configs, and that is why I want to ask - do you have any experience of using Istio over Liqo? Is exist recommendation to use Istio mesh in parallel with Liqo network peering? 

Thanks in advance!

**Comment by bcarlock-emerge** [comment]
I'd love to see a way to connect the Liqo overlay network to our Istio Mesh, an object that lets us set some manual routing, or best of all- a way to use Istio as the Liqo overlay network.
Istio's features like Canary deployments are of particular interest.

**Comment by aleoli** [comment]
Hi @Dima-Diachenko-work and @bcarlock-emerge!

> Maybe we're doing something wrong with configs, and that is why I want to ask - do you have any experience of using Istio over Liqo? Is exist recommendation to use Istio mesh in parallel with Liqo network peering?

At the moment, service meshes are not supported in Liqo. We did some tests in the past with Linkerd, and, in particular circumstances (e.g., non-overlapping and non-remapped clusters) some features partially worked. But we need to investigate deeper. Of course, you can use Istio in the namespaces or for the pod not offloaded with Liqo.

> I'd love to see a way to connect the Liqo overlay network to our Istio Mesh, an object that lets us set some manual routing, or best of all- a way to use Istio as the Liqo overlay network.

@bcarlock-emerge can you explain more about the feature this object would need?

**Comment by Dima-Diachenko-work** [comment]
@aleoli thank you for the answer! Got you. 
So we disabled Istio connection between clusters (left only default Liqo peering) and looks like it works for us.

**Comment by bcarlock-emerge** [comment]
@aleoli 
The routing object would need to be something akin to a routing table or Azure's User Defined Route. It could be as simple as a configmap that the route application consumes. It would need to be able to use DNS designations for next hop to be effective inside a kubernetes cluster probably.
