### ISSUE TITLE
Unable peer cluster - RKE certificate creation timeout

### ISSUE THREAD

**Issue by leitaof** [liqotech/liqo#1656]
#### What happened: 
Unable to peer clusters using OutOfBand or inbound.
We have deployed liqo into 2 k8s clusters and all pods are running properly on both.

See errors on first cluster in the control manager
E0202 15:45:45.891556       1 foreign-cluster-controller.go:218] Failed to ensure identity for remote cluster "ltec-fil": failed to send identity request: Post "https://10.195.177.52:31486/identity/certificate": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

On the second cluster we see this error in liqo-auth pod
E0202 15:46:10.947305       1 certificateIdentityProvider.go:149] context canceled before certificate retrieval
E0202 15:46:10.947375       1 identity.go:127] context canceled before certificate retrieval
E0202 15:46:10.947398       1 identity.go:61] context canceled before certificate retrieval
I0202 15:46:10.947491       1 trace.go:219] Trace[138064185]: "Identity handler" (02-Feb-2023 15:45:40.915) (total time: 30032ms):
Trace[138064185]: ["Identity handling" 30032ms (15:45:40.915)]
Trace[138064185]: [30.032229666s] [30.032229666s] END

#### What you expected to happen:
Authentication should go trough and cluster should be able to peer.

#### How to reproduce it (as minimally and precisely as possible):
Having two basic cluster created via rke tool v1.4.2 and deployed liqo v.0.7.0 via helm.

#### Environment:
- Liqo version: tested on v0.7.0 and v0.6.1
- Kubernetes version (use `kubectl version`): v1.23.15
- Cloud provider or hardware configuration: hardware
- Network plugin and version: canal_cni - rancher/calico-cni:v3.22.5-rancher1
- Install tools: helm v3 using other provider
- Others: We are using rke v1.4.2 to manage the k8s cluster

**Comment by aleoli** [comment]
Hi @leitaof!

RKE does not automatically issue the CSR required by Liqo for [authentication](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#x509-client-certs). You can enable this feature by adding the certificate signing files as described [in this issue](https://github.com/rancher/rancher/issues/14674#issuecomment-535234849).

**Comment by leitaof** [comment]
Hi Alessandro, 
Thanks for the reply,  adding the 2 config lines to kube-controller in the RKE to enable the CSR did fix the problem.
The clusters are now peering together.  

We can now test liqo with RKE clusters.

**Comment by aleoli** [comment]
Wonderful! Closing the issue
