### ISSUE TITLE
[Feature] Support privated AKS cluster during liqoctl install

### ISSUE THREAD

**Issue by Sharathmk99** [liqotech/liqo#1692]
**Is your feature request related to a problem? Please describe.**
With Private AKS cluster we are not able to use liqoctl install command to install liqo or generate `values.yaml` file due to `fqdn` is not present in AKS Get API
`cluster, err := aksClient.Get(ctx, o.resourceGroupName, o.resourceName)`

**Describe the solution you'd like**
We can pass fqdn during the install command and liqoctl should use the one passed on via arguments
`liqoctl install aks .... --fqdn=https://xxxxx:443`
I have made the changes to support this feature in my feature branch, if this is useful I'll open PR.

**Describe alternatives you've considered**

**Additional context**
Error I get from current liqoctl install command
```
 INFO  Installer initialized                                                                                                         
 ERRO  Error retrieving provider specific configuration: failed retrieving cluster information: failed to retrieve cluster APIServer FQDN, is the cluster running?
```

**Comment by aleoli** [comment]
Hi @Sharathmk99!

**Comment by Sharathmk99** [comment]
@aleoli  Thank you for your response.
Yes for now I have faced FQDN issue.

Sometime back I faced issues with Azure CNI, as Pod's IP and Kubernetes API server address were conflicting.
For now I'm testing with Kubenet CNI.
Will keep you posted if I face any other issues.
