### ISSUE TITLE
[Feature] Network improvements

### ISSUE THREAD

**Issue by frisso** [liqotech/liqo#1862]
Current networking in Liqo enables only two options:
* connect remote clusters with Wireguard
* disable Liqo networking and use a third party technology (e.g., Cilium or provider-based Virtual Private Connections)

This feature request proposes an enhancement of Liqo networking in the following directions:
- [x] Support for multiple peering technologies at the same time, in the same cluster (e.g., a peering using Wireguard, another using VPC)
- [ ] Support for more scalable interconnection technologies, without relying on third-party technologies such as VPC (e.g., vxlan?)
- [ ] Support for direct-connectivity between clusters without always relying on the "master" cluster. E.g., in a topology such as A-B-C, where "B" is the master, enable direct communication between A and C.

**Comment by aleoli** [comment]
The new liqo network module directly supports multiple technologies for different clusters.

The new Liqo extensibility (>=v1.0.0-rc.1) allows you to implement the other two points using the necessary technologies.
