### ISSUE TITLE
[Feature] Ability to select the storage class used by a liqo pvc.

### ISSUE THREAD

**Issue by tom-asmblr** [liqotech/liqo#1870]
Apologies if I've missed this in the documentation, but I couldn't find it anywhere.
Is it possible to define the storageClass used by the virtual liqo pvc? 

Thanks

**Comment by fra98** [comment]
@tom-asmblr virtual PVCs are created using the "liqo" storageClass. For each virtual PVC, a real PVC is created either on the local or remote cluster (depending on where the pod is scheduled, as explained here: https://docs.liqo.io/en/latest/usage/stateful-applications.html#liqo-virtual-storage-class). For real PVCs, you can set the storageClass using the Helm value `storage.realStorageClassName` (if not set, it will default to the default storageClass of the cluster hosting the real PVC).
