### ISSUE TITLE
Liqo on GKE initializing service type of liqo-gateway and liqo-auth services as ClusterIP, preventing peering

### ISSUE THREAD

**Issue by mfranzil** [liqotech/liqo#1923]
#### What happened:

When `liqoctl==0.8.3` is used to install Liqo on a GKE cluster, the `liqo-gateway` and `liqo-auth` services are (correctly) created with the ClusterIP setup (as in [the docs](https://cloud.google.com/kubernetes-engine/docs/concepts/service)). However, following the docs by heart and attempting to peer (both ib and oob) with the cluster results in the following error:

```
 ERRO   (local) an error occurred while retrieving WireGuard configuration:
 service {liqo/liqo-gateway} is of type {ClusterIP}, only types of {LoadBalancer}
 and {NodePort} are accepted
```

#### What you expected to happen:

Either throw an error during Liqo installation, prompting the user not to use ClusterIP and to use the network flag. 

#### How to reproduce it (as minimally and precisely as possible):

- Install `liqoctl==0.8.3`
- Create a GKE cluster and install Liqo with no network flags
- Create any other cluster and install Liqo with any configuration
- Attempt to peer both in-band and out-of-band with the cluster

#### Anything else we need to know?:

I am aware that the Liqo docs specify the network flags allowing to choose between ClusterIP, LoadBalancer and NodePort. I am also aware that users must read the documentation of their provider before installing Liqo.

However, this approach confuses users as unless they realize they need not to use ClusterIP, after receiving this error they will have to uninstall and re-install again (or edit services manually). Alternatively, GKE Liqo installation could by default point to LoadBalancer instead.

#### Environment:
- Liqo version: `0.8.3`
- Kubernetes version (use `kubectl version`): `v1.27.1`
- Cloud provider or hardware configuration: Clusters on GKE; running machine Ubuntu 22.04 LTS on x86_64

**Comment by cheina97** [comment]
Hi @mfranzil, can you provide us the command you used to install Liqo? Did you force the creation of ClusterIP services in some way? Did you customize the helm values?

What you are observing (the creation of a ClusterIP services) is not correct, Liqo should use a UDP LoadBalancer service for the liqo-gateway and a TCP LoadBalancer (or ClusterIP, in case it is exposed using an Ingress) for liqo-auth.

**Comment by mfranzil** [comment]
Hi, Liqo was installed with the following command:

```
liqoctl install gke --project-id ${GKE_PROJECT_ID} \
    --cluster-id ${GKE_CLUSTER_FIRST_ID} \
    --zone ${GKE_CLUSTER_FIRST_ZONE} \
    --credentials-path ${GKE_SERVICE_ACCOUNT_PATH} \
```

where I had to append `--service-type LoadBalancer` in order to make it work.

I did not do anything else (no Helm, no other forces): I followed the documentation on GKE by heart [here](https://docs.liqo.io/en/v0.8.3/installation/install.html), while I created the GKE cluster with this command:

```
gcloud beta container \
    --project "$GKE_PROJECT_ID" clusters create "$GKE_CLUSTER_FIRST_ID" \
    --zone "$GKE_CLUSTER_FIRST_ZONE" \
    --no-enable-basic-auth \
    --cluster-version "1.27.2-gke.1200" \
    --release-channel "stable" \
    --machine-type "e2-standard-2" \
    --image-type "UBUNTU_CONTAINERD" \
    --disk-type "pd-balanced" \
    --disk-size "100" \
    --metadata disable-legacy-endpoints=true \
    --scopes "https://www.googleapis.com/auth/devstorage.read_only","https://www.googleapis.com/auth/logging.write","https://www.googleapis.com/auth/monitoring","https://www.googleapis.com/auth/servicecontrol","https://www.googleapis.com/auth/service.management.readonly","https://www.googleapis.com/auth/trace.append" \
    --num-nodes "3" \
    --logging=SYSTEM,WORKLOAD \
    --monitoring=SYSTEM \
    --enable-ip-alias \
    --network "projects/$GKE_PROJECT_ID/global/networks/default" \
    --subnetwork "projects/$GKE_PROJECT_ID/regions/$GKE_CLUSTER_FIRST_REGION/subnetworks/default" \
    --enable-intra-node-visibility \
    --cluster-dns=clouddns \
    --cluster-dns-scope=cluster \
    --default-max-pods-per-node "110" \
    --security-posture=standard \
    --workload-vulnerability-scanning=disabled \
    --enable-dataplane-v2 \
    --enable-master-authorized-networks \
    --master-authorized-networks $WHITELISTED_CIDR \
    --addons HorizontalPodAutoscaling,HttpLoadBalancing,GcePersistentDiskCsiDriver \
    --enable-autoupgrade \
    --enable-autorepair \
    --max-surge-upgrade 1 \
    --max-unavailable-upgrade 0 \
    --enable-managed-prometheus \
    --enable-shielded-nodes \
    --enable-l4-ilb-subsetting \
    --node-locations "$GKE_CLUSTER_FIRST_ZONE"
```

All Bash variables you see are defined in the exact same way as in the docs (you may see some `_FIRST` around, since I had two clusters, both with the same problem). 

Once I introduced the ServiceType flag, everything worked smoothly (at least with an out-of-band peering).

**Comment by cheina97** [comment]
Hi @mfranzil, it is a well known bug of the CLI. It has been solved [here](https://github.com/liqotech/liqo/commit/2b8b99e0e7d286d164a2845a4a6124df093a973b), but we have not published a new release yet.
