### ISSUE TITLE
Liqo cannot peer Linode k8s clusters

### ISSUE THREAD

**Issue by Jdelachi** [liqotech/liqo#1972]
#### What happened:
Liqo peering is not working in Linode k8s clusters

#### What you expected to happen:
When I peer 2 Linode k8s cluster, it should peer it.

#### How to reproduce it (as minimally and precisely as possible):
-Create 2 Linode k8s cluster.
-Install Liqo on both clusters: `liqoctl install --api-server-url=<API-SERVER-URL> --pod-cidr=10.2.0.0/16 --service-cidr=10.128.0.0/16 --service-type=NodePort`
-Execute on cluster-a: `liqoctl generate peer-command`
-On cluster-b, execute the generated peer command above.
-It cannot peer.

#### Anything else we need to know?:
-Linode K8s cluster has always the same podCIDR (10.2.0.0/16) and serviceCIDR (10.128.0.0/16).
-Linode k8s uses Calico as CNI with the env variable `IP_AUTODETECTION_METHOD` set to `can-reach=192.168.128.1`.
-Calico is setup to uses IP in IP encapsulation for all inter workload traffic:

apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: default-ipv4-ippool
spec:
  cidr: 10.2.0.0/16
  ipipMode: Always
  natOutgoing: true
  nodeSelector: all()
  vxlanMode: Never

#### Environment:
- Liqo version: Client version v0.9.0
- Kubernetes version (use `kubectl version`): v1.26.7
- Cloud provider or hardware configuration: Linode LKE
- Network plugin and version: Calico v3.25
- Install tools: liqoctl
- Others:

**Comment by cheina97** [comment]
In the next days we are going to release the **0.9.4** version so will be easier for you to test. Anyway if you want to test it right now you can follow these instructions https://docs.liqo.io/en/v0.9.3/installation/install.html#install-development-versions

**Comment by Jdelachi** [comment]
Hi @cheina97 , I have tested the version 0.9.4 but the gateway endpoint uses the private Ip instead of the node public IP (as the problem in the version 0.9.3).

The command I executed: `liqoctl install --pod-cidr=10.2.0.0/16 --service-cidr=10.128.0.0/16 --service-type=NodePort`

**Comment by cheina97** [comment]
Hi @Jdelachi, at the moment you still need to use the flag to set the node IP.

**Comment by Jdelachi** [comment]
Specifying the node ip works, but from cluster-b it takes around 40 seconds to get the info when executing the following command:
`curl -s -H 'accept: application/json' http://flights-service.liqo-demo:7999/schedule | jq .`

If I execute the same command in the cluster-a, the response is immediate.

I'm following this example to test the service offloading: https://docs.liqo.io/en/v0.9.4/examples/service-offloading.html#offload-a-service

Is normal this performance is a remote cluster when we are dealing just with json payloads?
