### ISSUE TITLE
v0.9.3 on GKE results in the gateway crashing on add iptable rule

### ISSUE THREAD

**Issue by dhrp** [liqotech/liqo#1982]
#### What happened:

installing version v0.9.3 results in the gateway crashing, failing to add an iptables rule.
```
an error occurred while creating iptables handler: unable to insert iptable rule "-j LIQO-FORWARD": running [/sbin/iptables-nft -t filter -I FORWARD 1 -j LIQO-FORWARD --wait]:
```

I was running v0.9.3 before, without this issue. 

#### What you expected to happen:

I expected the gateway to start running

#### How to reproduce it (as minimally and precisely as possible):

```
$ liqoctl install gke --only-output-values \
--dump-values-path ${CLUSTER_NAME}-values.yaml \
--cluster-name ${CLUSTER_NAME} \
--cluster-id ${GKE_CLUSTER_ID} \
--project-id ${GKE_PROJECT_ID} \
--credentials-path ${GKE_SERVICE_ACCOUNT_PATH} \
--zone ${GKE_CLUSTER_ZONE}

$ helm install liqo liqo/liqo --namespace liqo \
       --values ./${CLUSTER_NAME}-values.yaml --create-namespace --version v0.9.3
```

#### Anything else we need to know?:

It seemed to work fine on v0.9.3

#### Environment:
- Liqoctl version: v0.9.3
- Liqo (helm) version: v0.9.3
- Kubernetes version (use `kubectl version`): Server Version: v1.27.3-gke.100
- Cloud provider or hardware configuration: Google Standard GKE cluster
- Network plugin and version: calico (?) -- whatever is the default on GKE
- Install tools:
- Others:

**Comment by fra98** [comment]
Hi @dhrp, are you using *Container-Optimized OS with containerd* (`cos_containerd`) or *Ubuntu with containerd* (`ubuntu_containerd`) as image type?

**Comment by cheina97** [comment]
Hi @dhrp, In addition to what @fra98 said, we recently changed the default iptables mode used by Liqo from iptables-legacy to iptables-nft. Please try to restore the legacy mode using --set networking.iptables.mode=legacy. If it works we can add it as the default behavior in GKE. Sorry for the inconvenient, at the moment we still don't have automatic tests on cloud providers.
