### ISSUE TITLE
Liqo route restarting due to Kubernetes API IO timeout

### ISSUE THREAD

**Issue by Sharathmk99** [liqotech/liqo#1987]
#### What happened:
Some of the Liqo Route pods is getting restarted due to IO timeout from Kuberentes API server while querying for discovery.liqo.io CRD. 
Is it possible to disable discovery because we don't auto peer the new cluster.

Error,
```
k logs liqo-route-zhdtg -n liqo --previous 
E0907 14:54:37.886389       1 mapper.go:109] Get "https://10.96.0.1:443/apis/discovery.liqo.io/v1alpha1?timeout=32s": dial tcp 10.96.0.1:443: i/o timeout
E0907 14:54:37.886524       1 mapper.go:53] Get "https://10.96.0.1:443/apis/discovery.liqo.io/v1alpha1?timeout=32s": dial tcp 10.96.0.1:443: i/o timeout
E0907 14:54:37.886555       1 cluster.go:202] "Failed to get API Group-Resources" err="Get \"https://10.96.0.1:443/apis/discovery.liqo.io/v1alpha1?timeout=32s\": dial tcp 10.96.0.1:443: i/o timeout"
E0907 14:54:37.886568       1 route-operator.go:116] unable to get manager: Get "https://10.96.0.1:443/apis/discovery.liqo.io/v1alpha1?timeout=32s": dial tcp 10.96.0.1:443: i/o timeout
```

#### What you expected to happen:
No restarts due to discovery CRD

#### How to reproduce it (as minimally and precisely as possible):
It's difficult to reproduce as it depends on Kubernetes API response

#### Environment:
- Liqo version: v0.9.1
- Liqoctl version: v0.9.1
- Kubernetes version (use `kubectl version`): 1.21
- Cloud provider or hardware configuration: AKS
- Node image:
- Network plugin and version: 
- Install tools:
- Others:

**Comment by aleoli** [comment]
Liqo route DaemonSet does not exist anymore, starting from Liqo v1.0.0-rc.1
