### ISSUE TITLE
[Feature] Setting the name of the configmap that contains the clusterID through the clusterconfig CRD

### ISSUE THREAD

**Issue by alacuku** [liqotech/liqo#202]
**Is your feature request related to a problem? Please describe.**
The name of the configmap that contains the clusterID is hardcoded. Throughout the code when the configmap is needed the name of the configmap is also hardcoded.

**Describe the solution you'd like**
The possibility to set the name of the configmap in the clusterConfig CRD. So all the components that need the clusterID can find the name of the configmap in the configuration.

**Comment by palexster** [comment]
Closing because of deprecation.
