### ISSUE TITLE
wrong arm64 binary format

### ISSUE THREAD

**Issue by schnidrig** [liqotech/liqo#2245]
#### What happened:

The binaries for arm64 linux (https://github.com/liqotech/liqo/releases/download/v0.10.1/liqoctl-linux-arm64) are not actually arm64 binaries but amd64.

#### What you expected to happen:

arm64 binaries

#### Environment:
- Liqo version: v0.10.1
- Liqoctl version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Node image:
- Network plugin and version:
- Install tools:
- Others:

**Comment by aleoli** [comment]
Hi @schnidrig! Thanks for your issue! This PR will fix it. At the moment, you can build it locally by running ```make ctl``` in the repo root folder.

**Comment by cheina97** [comment]
The releases binaries have been fixed
