### ISSUE TITLE
Gateway pod CrashLoopBackOff

### ISSUE THREAD

**Issue by albacanete** [liqotech/liqo#2316]
#### What happened:
The `liqo-gateway` pod does not start and loops in CrashLoopBackOff. The output of the logs is the following.
```
I0201 09:42:24.768246       1 gateway-operator.go:198] created custom network namespace {liqo-netns}
W0201 09:42:24.776632       1 driver.go:398] wireguard kernel module not present, falling back to the userspace implementation
I0201 09:42:24.776706       1 driver.go:407] Waiting for wireguard device to be created
E0201 09:42:24.776770       1 driver.go:409] failed to get wireguard device 'liqo.tunnel': Link not found
I0201 09:42:24.776792       1 driver.go:407] Waiting for wireguard device to be created
E0201 09:42:24.776842       1 driver.go:409] failed to get wireguard device 'liqo.tunnel': Link not found
I0201 09:42:25.777595       1 driver.go:407] Waiting for wireguard device to be created
I0201 09:42:25.778063       1 driver.go:134] Wireguard driver initialized with userspace implementation
I0201 09:42:25.782225       1 driver.go:165] created wireguard interface named liqo.tunnel with publicKey El5cagE9jF58fs1pzsI9K/Bn+4GhVk6M1uoc9OLOlAQ=
I0201 09:42:25.783651       1 driver.go:181] wireguard interface named liqo.tunnel, is up on i/f number 1756435, listening on port :5871, with key El5cagE9jF58fs1pzsI9K/Bn+4GhVk6M1uoc9OLOlAQ=
I0201 09:42:25.785546       1 tunnel-operator.go:515] created veth device {liqo.host} with index {1756436} in host netns with path {/proc/1/task/9/ns/net}
I0201 09:42:25.785564       1 tunnel-operator.go:517] created veth device {liqo.gateway} with index {2} in gateway netns with path {/run/netns/liqo-netns}
I0201 09:42:25.847517       1 receiver.go:142] conncheck receiver disconnect checker: started
I0201 09:42:25.847581       1 receiver.go:108] conncheck receiver: started
I0201 09:42:25.849052       1 iptables.go:160] Iptables version: 1.8.9, mode: nf_tables
E0201 09:42:25.852021       1 tunnel-operator.go:485] an error occurred while creating iptables handler: cannot create Liqo default chains: cannot retrieve chains in table -> filter : running [/sbin/iptables-nft -t filter -S --wait]: exit status 4: iptables v1.8.9 (nf_tables): Could not fetch rule set generation id: Invalid argument
E0201 09:42:25.852101       1 gateway-operator.go:210] an error occurred while creating the tunnel controller: cannot create Liqo default chains: cannot retrieve chains in table -> filter : running [/sbin/iptables-nft -t filter -S --wait]: exit status 4: iptables v1.8.9 (nf_tables): Could not fetch rule set generation id: Invalid argument
I0201 09:42:25.852130       1 gateway-operator.go:211] cleaning up gateway network namespace
I0201 09:42:25.852506       1 gateway-operator.go:215] cleaning up wireguard tunnel interface
```

#### What you expected to happen:
For the pod to be in running state. 

#### How to reproduce it (as minimally and precisely as possible):
The Kubernetes cluster is on-prem on Nvidia Jetsons and was bootstraped with `kubeadm` and has Flannel as CNI. 
liqo was boostraped with the following command: `liqoctl install kubeadm --service-type NodePort`

#### Environment:
- Liqo version: 
**v0.10.1**
- Liqoctl version: 
**v0.10.1**
- Kubernetes version (use `kubectl version`):
 **v1.28.4**
- Cloud provider or hardware configuration: 
**master**: Nvidia Jetson Orin Nano (arm64)
**node**: Nvidia Jetson AGX Orin (arm64)
- Node image:
- Network plugin and version:
**Flannel v0.24.2**
- Install tools:
- Others:

**Comment by frisso** [comment]
Hello @albacanete , nice to see friends here :-)
We don't have Jetson available here right now in our team, so not easy to debug. Could you please join our Slack (in the #help channel), so that interactions would be easier? I'm personally very very interested in this application.
Thanks!

**Comment by albacanete** [comment]
hello @frisso, nice to talk to you again :smile: 
I did, and the solution is to execute the liqo install comand specifying the legacy implementation of iptables 
`liqoctl install kubeadm --set networking.iptables.mode=legacy`

thank you!!

**Comment by albacanete** [comment]
hello @frisso, nice to talk to you again :smile: 
I did, and the solution is to execute the liqo install comand specifying the legacy implementation of iptables 
`liqoctl install kubeadm --set networking.iptables.mode=legacy`

thank you!!
