### ISSUE TITLE
Peering connection dropped

### ISSUE THREAD

**Issue by Papotto97** [liqotech/liqo#2330]
I installed liqo on "kind" provider for a local test. I tried to peer two single node clusters created via kind locally. Everything seemed to work correctly, when at a certain point, after restarting the cluster's docker container, the "liqoctl status peer" command gave me the result that the two clusters were no longer in a peering state as the connection was no longer active .

I expected that once both containers restarted, the connection would re-establish itself.

To reproduce the issue, simply restart the docker containers of both clusters.

Thanks in advance.

**Comment by cheina97** [comment]
Hi @Papotto97, it is a well-known problem.
Kind is not meant to be restarted, we use kind for development and we usually recreate the clusters every day.

**Comment by Papotto97** [comment]
Hi @cheina97, first of all, thank you for the reply.
Just out of curiosity, is this a problem related only to the "kind" provider or is it a problem also present on other platforms?
Thanks.

**Comment by cheina97** [comment]
> Hi @cheina97, first of all, thank you for the reply.
> Just out of curiosity, is this a problem related only to the "kind" provider or is it a problem also present on other platforms?
> Thanks.

Only on Kind 👍
