### ISSUE TITLE
Metrics from VirtualKubelet are not being gathered

### ISSUE THREAD

**Issue by EladDolev** [liqotech/liqo#2364]
By setting `virtualKubelet.metrics.podMonitor.enabled` to `true`, a PodMonitor would be successfully created, but no metrics would be gathered because the `metrics` port is absent on the VK Pod's spec

#### Environment:
- Liqo version: v.0.10.1
- Liqoctl version: v.0.10.1
- Kubernetes version (use `kubectl version`): 1.26
- Cloud provider or hardware configuration: GKE
- Node image: COS 105

**Comment by aleoli** [comment]
Hi @EladDolev,

I've just tried. It seems that the port is correctly added, and I'm able to curl it:

```txt
k get pods -n liqo-tenant-blue-sound-874edf vk-liqo-blue-sound-77dcbcbd97-k2hbf -o yaml | grep metrics -A 3 -B 3
    - --event-reflection-type=DenyList
    - --annotations-not-reflected=cloud.google.com/neg,cloud.google.com/neg-status,kubernetes.digitalocean.com/load-balancer-id,ingress.kubernetes.io/backends,ingress.kubernetes.io/forwarding-rule,ingress.kubernetes.io/target-proxy,ingress.kubernetes.io/url-map,metallb.universe.tf/address-pool,metallb.universe.tf/ip-allocated-from-pool,metallb.universe.tf/loadBalancerIPs
    - --enable-apiserver-support=true
    - --metrics-enabled=true
    - --metrics-address=:5872
    - --foreign-kubeconfig-secret-name=liqo-identity-g7tk2
    - --create-node=true
    command:
--
    name: virtual-kubelet
    ports:
    - containerPort: 5872
      name: metrics
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
```

Have you enabled this flag after the vk creation? If so, you should re-trigger the creation of the vk deployment by disabling and re-enabling the peering.

**Comment by EladDolev** [comment]
Thank you @aleoli , you're right 😄

**Comment by frisso** [comment]
@aleoli Would it be useful a patch to the documentation, maybe here?
https://docs.liqo.io/en/latest/usage/prometheus-metrics.html

**Comment by aleoli** [comment]
Hi @frisso! This is more general than metrics: only some fields (very few) are enforced and updated after the VK Pod creation.

This will change with the offloading module refactoring in future releases.
