### ISSUE TITLE
Pod stuck in Pending state in Consumer cluster

### ISSUE THREAD

**Issue by kaviankarimzadeh** [liqotech/liqo#2404]
#### What happened:
Hi, 
Just installed Liqo (tried both via liqoctl and helm) to test offloading/peering scenarios. Followed according to the docs and [example](https://docs.liqo.io/en/v0.10.1/usage/namespace-offloading.html#offloading-a-namespace) provided for Peering and namespace offloading:

##Liqo Installation command Consumer cluster (dc1):

    podCIDR: "10.246.0.0/20"
    serviceCIDR: "10.96.0.0/12"

```
liqoctl install kubeadm --cluster-labels topology.kubernetes.io/zone: nuremberg \
--cluster-name dc1 \
--context dc1 \
--enable-ha \
--service-type NodePort \
--sharing-percentage 90
```

![image](https://github.com/liqotech/liqo/assets/113193426/a96a193c-5ce0-4bb2-9dc4-daaa6e1a2be3)

##Liqo Installation command Provider cluster (dc2):

    podCIDR: "10.244.0.0/20"
    serviceCIDR: "10.96.0.0/12"

```
liqoctl install kubeadm --cluster-labels topology.kubernetes.io/zone: helsinki \
--cluster-name dc2 \
--context dc2 \
--enable-ha \
--service-type NodePort \
--sharing-percentage 90
```

![image](https://github.com/liqotech/liqo/assets/113193426/46d64683-6193-48d1-bf36-5fb4ee33a05e)

##Peer two clusters

##Provider (dc2) cluster:
```
liqoctl generate peer-command
```

##Consumer (dc1) cluster:
```
liqoctl peer out-of-band dc2 --auth-url https://2.2.2.2:30572 --cluster-id 961aa0d4-XXXX --auth-token <ec3e371509e7XXXX>
```

##Bidirectional peering
##Provider (dc2) cluster:
```
liqoctl peer dc1
```

##Checking status on Consumer (dc1) cluster:

![image](https://github.com/liqotech/liqo/assets/113193426/6ce38e36-77ac-4a7a-807b-d659bdc29951)

##Checking status on Provider (dc2) cluster:

![image](https://github.com/liqotech/liqo/assets/113193426/acc16703-6345-40a8-b2d0-7a00b9cc610a)

##Namespace Offloading

```
kubectl create namespace liqo-demo
liqoctl offload namespace liqo-demo --namespace-mapping-strategy EnforceSameName --pod-offloading-strategy LocalAndRemote
kubectl create -n liqo-demo deployment demo --image nginx:alpine --replicas 7
```

![image](https://github.com/liqotech/liqo/assets/113193426/5f092970-629f-47b0-899e-74ab7f2f32e1)

As you can see the pod which is scheduled on Consumer Cluser (dc1) is in Pending state but it's running in Provider Cluster (dc2):

Consumer (dc1)

![image](https://github.com/liqotech/liqo/assets/113193426/7ad933f1-83e0-47cf-9976-f89e3498d609)

Provider (dc2)

![image](https://github.com/liqotech/liqo/assets/113193426/0ea382e5-81e2-49ab-a7e1-f1d89efba171)

Observing this error in vk-liqo-dc2 pod on Consumer Cluster (dc1):

```
E0324 13:07:03.902034       1 podns.go:434] Failed to update local pod status "liqo-demo/demo-55d6d7b767-htsg9" (remote: "liqo-demo/demo-55d6d7b767-htsg9"): Pod "demo-55d6d7b767-htsg9" is invalid: status.hostIPs[0].ip: Invalid value: "65.109.X.X": must be equal to `hostIP`
```
`65.109.X.X` is one of Provide Cluster Worker node IP.

Here is the Pod status info in Consumer Cluster which is in Pending state:
```
status:
  phase: Pending
  conditions:
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2024-03-24T13:01:39Z'
  hostIP: 10.246.2.119
  qosClass: BestEffort
```

And here is the Pod status info in Provider Cluster which is in Runing state:
```
status:
  phase: Running
  hostIP: 65.109.X.X
  hostIPs:
    - ip: 65.109.X.X
  podIP: 10.244.1.238
  podIPs:
    - ip: 10.244.1.238
```

Could please give me a hint what would be the issue or am I missed something here. Thanks

#### What you expected to happen:
The Pods would be up and running in both clusters.

#### Environment:
- Liqo version: v0.10.1
- Liqoctl version:
    Client version: v0.10.1
    Server version: v0.10.1
- Kubernetes version (use `kubectl version`): v1.29.2
- Cloud provider or hardware configuration: Hetzner Cloud
- Network plugin and version: Cilium CNI

**Comment by fra98** [comment]
Hi @kaviankarimzadeh this is a known bug on our end, it should be fixed if you use the latest commit on master. 
Note: we are planning a small patch release (0.10.2) also.

**Comment by kaviankarimzadeh** [comment]
Thanks @fra98 
I can confirm that issue has been fixed now with latest commit on master branch:

```
liqoctl install kubeadm --version f72d0fe7cf40ae9cc5e64e3b683e5b701c7e3532 --repo-url https://github.com/liqotech/liqo.git --cluster-labels topology.kubernetes.io/zone: nuremberg \
--enable-ha \
--service-type NodePort \
--sharing-percentage 90
```
#Consumer Cluster (dc1)

![image](https://github.com/liqotech/liqo/assets/113193426/0a1d6c04-8b61-4307-9bd9-fe4c6e859e66)

#Provider Cluster (dc2)

![image](https://github.com/liqotech/liqo/assets/113193426/9d070981-a36d-47d1-b1e7-55465fad5311)

**Comment by kaviankarimzadeh** [comment]
Thanks @fra98
I can confirm that issue has been fixed now with latest commit on master branch:

```
liqoctl install kubeadm --version f72d0fe7cf40ae9cc5e64e3b683e5b701c7e3532 --repo-url https://github.com/liqotech/liqo.git --cluster-labels topology.kubernetes.io/zone: nuremberg \
--enable-ha \
--service-type NodePort \
--sharing-percentage 90
```

##Consumer Cluster (dc1)

![image](https://github.com/liqotech/liqo/assets/113193426/e617eca5-8599-4daa-b404-49014c14b167)


##Provider cluster (dc2)

![image](https://github.com/liqotech/liqo/assets/113193426/b6ec0993-558f-43ea-9b1c-3a96d9befe6a)
