### ISSUE TITLE
Does Liqo support cephfs pvc offloading?

### ISSUE THREAD

**Issue by quanduy1710** [liqotech/liqo#2407]
Hi guys,
I have been trying Liqo for my project with 2 RKE clusters using ceph-csi-cephfs as my storage solutions.

I have been looking around in Liqo documents for some instruction but  found nothing but a note that said "In addition to the provided storage class, Liqo supports the execution of pods leveraging cross-cluster storage managed by external solutions (e.g., persistent volumes provided by the cloud provider infrastructure)"

I am wondering if Liqo can offload cephfs PvCs. Have anyone tried this before? 
Please leave a comment.
Thanks

**Comment by aleoli** [comment]
No issue with Ceph: Liqo offloads any PVC with the liqo storage class; it is a virtual storage class. It will use the storage class existing in the remote cluster; liqo does have in-tree storage support.
