### ISSUE TITLE
Broadcaster fails to update the PeeringRequest

### ISSUE THREAD

**Issue by fraborg** [liqotech/liqo#254]
**Describe the bug**
The remote watcher in the broadcaster module fails to update the `PeeringRequest` with the status of the `Advertisement` (Accepted/Refused).

**To Reproduce**
1. Install Liqo
2. `kubectl logs -n liqo broadcaster-<clusterID>`
3. In the log, read the error message

**Expected behavior**
The `PeeringRequest` should be updated with the status of the `Advertisement`.

**Screenshots**
![Schermata del 2020-09-11 16-40-00](https://user-images.githubusercontent.com/38689119/93062832-bbc3cf80-f675-11ea-99de-9ea1b535a332.png)

**Comment by palexster** [comment]
@fraborg @aleoli is this still open?

**Comment by fraborg** [comment]
yes, now that I've finished with the virtualKubelet I start addressing this and #245
