### ISSUE TITLE
[Feature] Improve GatewayServer declerative setup in 1.0

### ISSUE THREAD

**Issue by EladDolev** [liqotech/liqo#2732]
**Is your feature request related to a problem? Please describe.**

With current implementation, creating the `GatewayServer` resource would generate a `Secret` resource with a key pair **unless** a secret already exists.
That makes it very hard for declarative setup that uses `SealedSecret` for example for creating this `Secret` as the sealed-secrets controller would refuse to touch the `Secret` if it already exists, hence there's a race condition here

**Describe the solution you'd like**

A way of preventing automatically creating the `Secret` resource with a key pair when creating the `GatewayServer` resource

**Describe alternatives you've considered**

I have no alternatives other than manual intervention or manual setup which kinda beats the purpose of declarative setup

**Comment by claudiolor** [comment]
Fixed with #2747
