### ISSUE TITLE
Custom namespace, unable to authenticate 

### ISSUE THREAD

**Issue by remmen-io** [liqotech/liqo#2858]
#### What happened:

Using a custom namespace `kube-liqo` the command ` liqoctl authenticate -n kube-liqo --context k8s-consumer --remote-context k8s-provider` fails with 

```
 ➜ liqoctl authenticate -n kube-liqo --context k8s-consumer --remote-context k8s-provider
 ERRO   (remote) error: an error occurred while retrieving cluster id: Error from server (NotFound): configmaps "configmaps" not found
```

Liqo is installed an healty in the correct namespace

```
➜ liqoctl info
 ERRO  Liqo is not installed in the current cluster!

       You can install liqo via the 'liqoctl install' command.
       Check 'liqoctl install --help' for further information.

➜ liqoctl info -n kube-liqo
┌─ Local installation info ────────────────────────────────────────────────────────┐
|  Cluster ID:     k8s-consumer                                             |
|  Version:        v1.0.0-rc.2                                                     |
|  K8s API server: https://172.16.182.243:6443                                     |
|  Cluster labels                                                                  |
|      liqo.io/provider: kubeadm                                                   |
└──────────────────────────────────────────────────────────────────────────────────┘
┌─ Installation health ────────────────────────────────────────────────────────────┐
|  ✔    Liqo is healthy                                                            |
└──────────────────────────────────────────────────────────────────────────────────┘
┌─ Active peerings ────────────────────────────────────────────────────────────────┐
|                                                                                  |
└──────────────────────────────────────────────────────────────────────────────────┘
```` 

#### What you expected to happen:
Same behavior as with the `liqo`ns

#### How to reproduce it (as minimally and precisely as possible):

Use a non-default namespace
#### Environment:
- Liqo version: v1.0.0-rc.2
- Liqoctl version: v1.0.0-rc.2
- Kubernetes version (use `kubectl version`):  v1.30.5
- Cloud provider or hardware configuration: BareMetal with Talos
- Node image:
- Network plugin and version: Cilium v1.15.10-cee
- Install tools:
- Others:

**Comment by remmen-io** [comment]
When trying to follow the manual steps I get the same error with `liqoctl -n kube-liqo generate tenant ...`

**Comment by claudiolor** [comment]
Hey @remmen-io,
I believe that the issue here is that you did not provide the namespace where Liqo is installed also in the provider cluster. 
Can you try to provide the `--remote-namespace` argument to `liqoctl authenticate`, by specifying the namespace where Liqo is installed in the provider cluster?

In the case of `liqoctl generate tenant`, `-n` refers to the namespace where you want to generate the resource. The namespace where Liqo is installed can be specified via the `--liqo-namespace` argument.

Let me know if this fixes your issue 😊

**Comment by remmen-io** [comment]
Thanks a lot, this solved it.
Haven't read the help pages carefully enough
