### ISSUE TITLE
Unclear documentation about manually configuring liqo using CRs

### ISSUE THREAD

**Issue by remmen-io** [liqotech/liqo#2859]
I would like to deploy liqo using gitops principals with ArgoCD.

As the documentation describes for manual [authentication ](https://docs.liqo.io/en/v1.0.0-rc.2/advanced/peering/inter-cluster-authentication.html#inter-cluster-authentication):
```
The authentication process can be manually performed using liqoctl authenticate command or by manually applying the CRs.
```

Is there an overview of all the resources needed to configure authentication and namespace offloading with liqo?
For instance: In the manual installation steps for creating the nonce  `liqoctl create nonce` is used. This will create a new namespace and a secret.

I could extract this information, but it's cumbersome.

#### Environment:
- Liqo version: v1.0.0-rc.2
- Liqoctl version: v1.0.0-rc.2
- Kubernetes version (use kubectl version): v1.30.5
- Cloud provider or hardware configuration: BareMetal with Talos
- Node image:
- Network plugin and version: Cilium v1.15.10-cee
- Install tools:
- Others:

**Comment by claudiolor** [comment]
Hi @remmen-io, thanks for opening this issue.

With Liqo v1.0.0-rc.2 declaratively configuring the authentication is not actually trivial, as it requires an exchanges of resources between the consumer and the provider clusters.
With the new version of Liqo we simplified this procedure and we did a good amount of work to improve the compatibility with tools like ArgoCD. 

You can find [here](https://docs.liqo.io/en/latest/advanced/peering/peering-via-cr.html) a guide where we explain how to configure the peering between two clusters by applying the Liqo CRs. Note that to follow this guide, you will need the latest version of Liqo (which we are planning to release by the next week).
If you already want to try it, you can install the version of Liqo in the main branch, by providing the hash of the latest commit in main. E.g.:

```bash
liqoctl install [..args] --version <COMMIT_HASH_IN_MAIN_BRANCH>
```

or with Helm, by cloning the repository, from the root directory of the repo:

```bash
helm install liqo ./deployments/liqo [...args] --tag <COMMIT_HASH_IN_MAIN_BRANCH>
```
