### ISSUE TITLE
Virtual kubelet to-do list

### ISSUE THREAD

**Issue by mlavacca** [liqotech/liqo#367]
## Description

The virtual kubelet has to be enriched with some additional modules and to see its code refactored in some parts.

### New features
* implement metrics API (Ref. #426)
* add the vk deployment as owner reference for the `NamespaceNattingTable`
* implement `podUpdate`

## refactoring

* `virtualNodeUpdater` better integration
* old logs package deletion
* old and useless flags deletion
* `server.go` file refactoring
* deletion of all unused tracing functionalities

**Comment by palexster** [comment]
I would add the following items:
```:
- [ ] kubectl cp
- [ ] kubectl port-forward
```
