### ISSUE TITLE
[Feature] Custom resource naming and labeling

### ISSUE THREAD

**Issue by mlavacca** [liqotech/liqo#434]
**Is your feature request related to a problem? Please describe.**
Until now we used a bad approach for the naming of some resources: we forced the name by using the cluster-id as the name suffix. In Kubernetes it is pretty unusual: we should name the resources in a way that is agnostic to the remote cluster the resource itself is associated with, and prefer using labels for associating the resources to the remote cluster (`tunnelEnpoint` uses already this approach).

The resources affected by this problem are:
* `advertisement`
* `peeringRequest`
* `namespaceNattingTable`

**Describe the solution you'd like**
To replace their name with an automatic generated name (providing only a suffix to the API server) and to refer to the remote cluster by means of a label (`liqo.io/cluster-id` or something similar)

**Comment by palexster** [comment]
Closing as resources mentioned in the issue are deprecated.
