### ISSUE TITLE
[Feature] CRD replicator readiness probe

### ISSUE THREAD

**Issue by mlavacca** [liqotech/liqo#522]
This issue is related to #521. Whenever the CRDReplicator starts, it gets the `ClusterID` from a configmap. If the configmap has not been created yet, it should not appear as ready. Enforce the notReady status by using a `readinessProbe` and setting it to ready after the `clusterID` fetch.

https://github.com/liqotech/liqo/blob/756e9c1cf297a7370c1f151d45745719a0c63b28/cmd/crd-replicator/main.go#L51

**Comment by lomluca** [comment]
What do you about touching a file (i.e. `/tmp/cluster-id-acquired`) after the function call (if no error, of course) and setting a readinessProbe which tries to cat this file? If is it okay for you, I can implement this.

**Comment by mlavacca** [comment]
Yes, it fits our needs, but Kubebuilder provides a way to set up a handler for the readiness probes as described in the [`AddReadyzCheck`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/manager#Manager) field of the manager struct. I think it would be very nice to leverage this feature to implement the readiness probe.

Just a brief consideration: without the implementation of #521, addressing this issue is relatively useless: for the time being, the container crashes if the `clusterID` is not found yet, hence we cannot take advantage of this probe.
Anyway, feel free to address this issue: disregarding whether it is addressed before or after #521, it is a nice addition to the code.

**Comment by giorio94** [comment]
Closing, as superseded.
