### ISSUE TITLE
The ForeignCluster status is not populated if the authUrl is unreachable

### ISSUE THREAD

**Issue by giorio94** [liqotech/liqo#599]
**Describe the bug**

A ForeignCluster resource with an unreachable authUrl field does not provide any information for troubleshooting, as the status field is not populated as if it were not recognized by the controllers. 

**To Reproduce**
1. Create a ForeignCluster with discoveryType: Manual and an unreachable authUrl
2. Check the status of the resource

**Expected behavior**
The ForeignCluster should be in a "Failed" condition, with a message like "Impossible to reach the Liqo Authentication Endpoint at ..." as reason

**Comment by aleoli** [comment]
Closing, as addressed #879
