### ISSUE TITLE
Support for user-defined ExternalCIDR

### ISSUE THREAD

**Issue by davidefalcone1** [liqotech/liqo#633]
Currently, the ExternalCIDR has a fixed mask (same mask as PodCIDR) and it is chosen by the IPAM right after the installation of Liqo, by looking at the available networks.

It would be nice to allow the user to specify the ExternalCIDR (as a parameter to the network-manager) and return an error if it is already reserved.

**Comment by rverma-nsl** [comment]
I would even suggest to add support for an external IPAM too, something like https://docs.aws.amazon.com/vpc/latest/ipam/what-it-is-ipam.html. This will help organisations to pinpoint ip based activities much faster.
