### ISSUE TITLE
Hope to be able to run on the arm64 architecture.

### ISSUE THREAD

**Issue by laik** [liqotech/liqo#835]
☁  ~  curl -sL https://get.liqo.io | bash

     /$$       /$$
    | $$      |__/
    | $$       /$$  /$$$$$$   /$$$$$$
    | $$      | $$ /$$__  $$ /$$__  $$
    | $$      | $$| $$  \ $$| $$  \ $$
    | $$      | $$| $$  | $$| $$  | $$
    | $$$$$$$$| $$|  $$$$$$$|  $$$$$$/
    |________/|__/ \____  $$ \______/
                        | $$
                        | $$
                        |__/

[PRE-FLIGHT] architecture 'arm64' unknown [FATAL]

**Comment by palexster** [comment]
Hi @laik, thanks for reporting this issue!

I've tested this morning on my RPI, and I got:
```
ubuntu@toad:~$  curl -sL get.liqo.io | bash


     /$$       /$$
    | $$      |__/
    | $$       /$$  /$$$$$$   /$$$$$$
    | $$      | $$ /$$__  $$ /$$__  $$
    | $$      | $$| $$  \ $$| $$  \ $$
    | $$      | $$| $$  | $$| $$  | $$
    | $$$$$$$$| $$|  $$$$$$$|  $$$$$$/
    |________/|__/ \____  $$ \______/
                        | $$
                        | $$
                        |__/


[PRE-FLIGHT] [KUBECTL] Kubectl correctly found
[PRE-FLIGHT] [KUBECTL] Using KUBECONFIG: ~/.kube/config
[PRE-FLIGHT] [KUBECTL] Using context: default
[PRE-FLIGHT] [DOWNLOAD] Using curl to download files
[PRE-FLIGHT] [DOWNLOAD] Downloading Liqo (version: v0.3-rc.1)
[PRE-FLIGHT] [DOWNLOAD] Downloading Helm v3.5.3
[INSTALL] [CONFIGURE] Using namespace: liqo
[INSTALL] [CONFIGURE] Cluster name: LiqoCluster1558
[...]
```
So, it does work with certain arm64 boards. I think the problem is that the installer considers aarch64 as the code in uname for arm64. It should be sufficient to add also arm64 at https://github.com/liqotech/liqo/blob/5f7fd817c2fadb67f1f2ec00fdfa2d80a712af34/install.sh#L215 

For example, I have this output on my RPI:
```
ubuntu@toad:~$ uname -a
Linux toad 5.4.0-1038-raspi #41-Ubuntu SMP PREEMPT Thu Jun 17 14:14:11 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

Before doing the PR, can you please run a "uname -a" on your Linux box to double-check?

**Comment by aleoli** [comment]
Hi @laik, are you working on an Apple M1 or on a Linux system? I tested on a darwin arm64 system and we have some undergoing work required before being able to use the getting started

**Comment by laik** [comment]
Hi @aleoli , I use it on Apple M1

**Comment by aleoli** [comment]
Hi @laik, the current Liqo installer will be deprecated soon. A new CLI tool `liqoctl` will replace it in the next release.

I successfully tested Liqo on my M1 MacBook with the new installer, creating locally two kind clusters like that:
```yaml
# liqo-cluster-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  serviceSubnet: "10.90.0.0/12"
  podSubnet: "10.200.0.0/16"
nodes:
  - role: control-plane
    image: kindest/node:v1.21.1
  - role: worker
    image: kindest/node:v1.21.1
```

And deploying the two clusters:
```bash
kind create cluster --name liqo-cluster-1 --kubeconfig liqo_kubeconf_1 --config liqo-cluster-config.yaml --wait 2m
kind create cluster --name liqo-cluster-2 --kubeconfig liqo_kubeconf_2 --config liqo-cluster-config.yaml --wait 2m
```

Now, you can get the `liqoctl` binary for your platform typing:
```bash
wget -O liqoctl https://github.com/liqotech/liqo/releases/download/v0.3.0-rc.3/liqoctl-darwin-arm64 && chmod +x liqoctl
```

Now, you can install Liqo on your first cluster using the CLI tool
```bash
export KUBECONFIG=liqo_kubeconf_1
./liqoctl install --provider kind --version v0.3.0-rc.3
```

Once the installation finishes, you can install it similarly on the second cluster
```bash
export KUBECONFIG=liqo_kubeconf_2
./liqoctl install --provider kind --version v0.3.0-rc.3
```

You should see the two clusters automatically discover and peer each other in few seconds, and two new virtual nodes (one per cluster) will be created.

Please, can you confirm that this is working on your machine too? Ask here if you need further details
