### ISSUE TITLE
Namespace offloading initialisation window

### ISSUE THREAD

**Issue by aleoli** [liqotech/liqo#924]
#### What happened:

The creation of a `liqo/enabled` labeled namespace and a rapid creation of a pod in it with a node selector to match remote node only, will give us a forever pending pod. The pod cannot be scheduled on local nodes for the label selector and it cannot tolerate the virtual node taint.

#### What you expected to happen:

The pod creation is refused until the namespace configuration is completed. If a namespace has the `liqo/enabled` label, but there is still no `NamespaceOffloading` resource, it would not be possible to create pods.

#### How to reproduce it (as minimally and precisely as possible):

Apply a file containing both the labeled namespace and the pod, observe that the pod will keep in pending state.

#### Environment:
- Liqo version: v0.3.0
- Cloud provider or hardware configuration: kind
- Install tools: liqoctl

**Comment by giorio94** [comment]
Closing, as this limitation is intrinsic in the adopted approach, and a solution to address the problem (i.e., the addition of an appropriate label to the namespace at creation time) has been described in the documentation: https://docs.liqo.io/en/v0.5.2/usage/namespace-offloading.html#offloading-a-namespace
