### ISSUE TITLE
Maximum request rate per connection

### ISSUE THREAD

**Issue by dberecz** [liqotech/liqo#943]
#### What happened:
It is rather a question than a bug as of now. I did a quick performance evaluation of Liqo.
I had one AKS in West US and a GKE in West EU. 

A pod with an HTTP API was offloaded from GKE to AKS. In GKE I started a pod with the `wrk` tool and started to hit the pod offloaded to AKS. The latency numbers were okay, but one weird thing was that the number of requests send during a specific amount of time was always the same:
```
root@netperf:/wrk# wrk -t4 -c40 -d30s --latency http://hello-world-service:8080/api/hello
Running 30s test @ http://hello-world-service:8080/api/hello
  4 threads and 40 connections
  [...]
  3920 requests in 30.05s, 754.14KB read
```
```
root@netperf:/wrk# wrk -t4 -c40 -d30s --latency http://hello-world-service:8080/api/hello
Running 30s test @ http://hello-world-service:8080/api/hello
  4 threads and 40 connections
  [...]
  3920 requests in 30.05s, 753.26KB read
```
```
root@netperf:/wrk# wrk -t4 -c1 -d30s --latency http://hello-world-service:8080/api/hello
Running 30s test @ http://hello-world-service:8080/api/hello
  4 threads and 1 connections
  [...]
  98 requests in 30.06s, 18.65KB read
```

If connection was created with other tool than Liqo, the number of requests sent slightly varied during execution, as expected.

Do you maybe have an idea why that could happen?

#### What you expected to happen:
Number of requests sent slightly varies during execution.

#### Environment:
- Liqo version: 0.3.0
- Kubernetes version (use `kubectl version`):
**GKE**
`Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.10-gke.301", GitCommit:"17ad7bd6afa01033d7bd3f02ce5de56f940a915d", GitTreeState:"clean", BuildDate:"2021-08-24T05:18:54Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}`
**AKS**
`Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"8dc42052754bfacb111a0426830122dd9cc9cfa0", GitTreeState:"clean", BuildDate:"2021-08-31T00:01:04Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration:
**GKE**
Public GKE cluster with default VPC networking
**AKS**
Public AKS cluster with default Kubenet networking
- Network plugin and version:
- Install tools:
- Others:

**Comment by alacuku** [comment]
Hi @dberecz, making a similar test as you in a local environment I get different number of request for each run:

Run 1:
```
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     6.02ms    3.59ms  46.13ms   73.69%
    Req/Sec     6.33k   500.21     7.44k    68.56%
  Latency Distribution
     50%    5.62ms
     75%    7.81ms
     90%   10.07ms
     99%   18.49ms
  188832 requests in 30.00s, 1.31GB read
Requests/sec:   6293.96
Transfer/sec:     44.81MB
```

Run 2:
```
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     5.92ms    3.28ms  37.78ms   70.81%
    Req/Sec     6.38k   539.53     7.48k    68.90%
  Latency Distribution
     50%    5.65ms
     75%    7.76ms
     90%    9.73ms
     99%   16.51ms
  190384 requests in 30.00s, 1.32GB read
Requests/sec:   6345.14
Transfer/sec:     45.17MB
```
Run 3:
```
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     5.83ms    3.30ms  41.00ms   74.21%
    Req/Sec     6.46k   442.59     7.43k    67.22%
  Latency Distribution
     50%    5.51ms
     75%    7.42ms
     90%    9.49ms
     99%   17.07ms
  193185 requests in 30.05s, 1.34GB read
Requests/sec:   6428.61
Transfer/sec:     45.77MB
```

What is the number of requests when the clusters are interconnected with a tool other than Liqo?
