### ISSUE TITLE
[Feature] Extend liqoctl version to the installed chart version

### ISSUE THREAD

**Issue by palexster** [liqotech/liqo#955]
`liqoctl version` shows the client version. Similarly to kubectl version, we would like to show the installed version on the cluster.

Current output:

```
liqoctl version
Current Liqoctl client version: v0.3.1-alpha.2
```

Desired Output:
```
Current Liqoctl client version: v0.3.1-alpha.2
Current Liqo server version: v0.3.1-alpha.2
```

**Comment by giorio94** [comment]
Closing, as implemented in #1230
