### ISSUE TITLE
[Feature] Remove Incoming Peering

### ISSUE THREAD

**Issue by aleoli** [liqotech/liqo#957]
**Is your feature request related to a problem? Please describe.**
The possibility to disable an incoming peering with `liqoctl`.

**Describe the solution you'd like**
A simple `liqoctl` subcommand to disable the incoming peering for this cluster, to stop the resource sharing and remove the pod scheduled by the remote cluster on the local one.

**Comment by tsusadivyago** [comment]
Hi,

I want to contribute to liqo project. 
Note: This is my first time contributing to an open source. Will require some initial help to get familiar and learn. 
Can this atsk be assigned to me?

**Comment by aleoli** [comment]
Hi @tsusadivyago!

Nice to hear that. Yes, you can do it, we will help you.

In our opinion, this feature could be implemented by adding a new `--incoming` flag to the `liqoctl peer` and `unpeer` commands which sets the appropriate flag in the ForeignCluster resource (`.spec.incomingPeeringEnabled`). The idea is that the command with no flag should handle the outgoing peering. Additionally, you could add a `--all` flag to handle both at the same time.

**Comment by hamzalsheikh** [comment]
Is this issue still relevant? Happy to work on it if no one is.

**Comment by aleoli** [comment]
Hi @hamzalsheikh! The peering process will be refactored in the future but not in the next months. If you want to work on it, it is very appreciated!

**Comment by hamzalsheikh** [comment]
I just want to make sure I understand the requirement correctly after skimming the codebase and running the example.

In the current state, the peer command handles the outgoing peering. That is, creating an outgoing peering from the local cluster to the remote one. This is a unidirectional relation, with `.spec.incomingPeeringEnabled` in the remote cluster and disabled in the local by default.

What we want:
- `peer` stays the same.
- Running `peer --incoming false ... ` in the remote cluster stops the established relation.
- Running `peer --incoming true ...` in the local cluster makes the established relation bidirectional.
- Running `peer --all` directly establishes a bidirectional connection between the clusters.

Please assign me if all is well.

**Comment by aleoli** [comment]
`.spec.incomingPeeringEnabled` indicates whether the peering coming from that cluster should be accepted; it does not perform any action. By default, it is set to Auto, similar to Yes.

When it is set to No, it refuses the peering from the other cluster, leaving it pending. I think we should add a flag in liqoctl to handle this field.

* running `peer --incoming` will set this field to Yes, allowing peerings
* running `unpeer --incoming` will set this field to No, disallowing peering

Additionally, you can design a bidirectional peer command, but you need both kubeconfigs. For some aspects, it is similar to what the peer in-band command is doing. That is something that we can do, but it is a different step and requires some more changes.
